### ISSUE TITLE
Incorrect Wi-Fi signal strength (RSSI)

### ISSUE THREAD

**Issue by SuperXL2023** [openshwprojects/OpenBK7231T_App#1005]
All the time Wi-Fi signal strength is shown like -1 dBm (excellent). This cannot be, because the Wi-Fi module is located at a distance from the router (5-10 meters). This signal strength is displayed both in the web interface and in MQTT
For me personally, this is a very important parameter, because the switch is located in a socket in a solid reinforced concrete wall, and in case of any problems or lack of correct operation of the device, I can always do an analysis of the signal level, which will tell me where the problem is, whether the Wi-Fi is weak or hardware problems or something else.

**Firmware:**

**- Version:** 1.17.366 (Build on Dec 17 2023 22:12:41)
**- Device:** Wall light switch, discussed [Info on BL602 Module SDV-002_V1.2 from Aliexpress 3-Gang Switch, Pin Compatibility & GPIOs](https://www.elektroda.com/rtvforum/topic3970659.html)
**- Chip/model:** BL602L20 / Module SDV-002_V1.2

P.S. This is my first issue, please don't push me too hard.

**Comment by openshwprojects** [comment]
Hello, I think that the RSSI display on BL602 may be just a placeholder. It's not a very popular platform. We need to look into that.
