### ISSUE TITLE
ISNATCH HeySwitch

### ISSUE THREAD

**Issue by davidebeatrici** [openshwprojects/OpenBK7231T_App#1007]
[Scheda tecnica 68.6810.65_1.pdf](https://github.com/openshwprojects/OpenBK7231T_App/files/13755233/Scheda.tecnica.68.6810.65_1.pdf)
[HEY SWITCH 68.6810.65 Manuale ITA-ENG.pdf](https://github.com/openshwprojects/OpenBK7231T_App/files/13755232/HEY.SWITCH.68.6810.65.Manuale.ITA-ENG.pdf)
[cod. 68.6810.65 - Dichiarazione di Conformità_1.pdf](https://github.com/openshwprojects/OpenBK7231T_App/files/13755231/cod.68.6810.65.-.Dichiarazione.di.Conformita_1.pdf)

<details>
<summary>Pictures</summary>

![1](https://github.com/openshwprojects/OpenBK7231T_App/assets/5897523/c01f782b-d4e2-414e-82dd-687572792ab1)
![2](https://github.com/openshwprojects/OpenBK7231T_App/assets/5897523/a84a9349-a6b5-48dd-8fb1-95e44fbec755)
![3](https://github.com/openshwprojects/OpenBK7231T_App/assets/5897523/e2d07b18-6553-422d-a361-fcaf289b8181)
![4](https://github.com/openshwprojects/OpenBK7231T_App/assets/5897523/1f24a873-644b-4705-9153-124bd858a750)
![board_bottom](https://github.com/openshwprojects/OpenBK7231T_App/assets/5897523/af7d0e14-0f79-4f0b-97f2-8ea688dbc291)
![board_top](https://github.com/openshwprojects/OpenBK7231T_App/assets/5897523/27c78167-7152-457b-b1f1-86bdd3c02562)
![chip](https://github.com/openshwprojects/OpenBK7231T_App/assets/5897523/18e61d65-fd04-456d-9609-38aea6818744)
</details>

The MCU appears to be a `BK7231Q`: https://docs.libretiny.eu/boards/wa2

I'll attempt to perform a flash and report the result here.

**Comment by davidebeatrici** [comment]
Oh, I just realized only the `BK7231N` and `BK7231T` are mentioned as supported by this project... can anyone confirm?

**Comment by openshwprojects** [comment]
there is no known project supporting WA2 as fas a I know, but you can post your results there:
https://www.elektroda.com/rtvforum/viewtopic.php?p=20859869#20859869

**Comment by davidebeatrici** [comment]
I ended up replacing the module with an `ESP8685-WROOM-03`:

![](https://github.com/user-attachments/assets/3e321902-a312-40a8-a12b-c89c23052824)

And also replaced the button with an external one:

![](https://github.com/user-attachments/assets/e0c9e9fe-5766-405b-a49f-aee0755f5ad4)
