### ISSUE TITLE
CFG_GetDeviceName

### ISSUE THREAD

**Issue by PeterPolacek** [openshwprojects/OpenBK7231T_App#101]
I cant compile because CFG_GetDeviceName
D:\git\bk7231\openbk7231n-master\platforms\bk7231n\bk7231n_os/beken378/func/lwip_intf/lwip-2.0.2/port/ethernetif.c:140: undefined reference to `CFG_GetDeviceName'

What i am doing wrong?

Thank you

**Comment by openshwprojects** [comment]
What are you compiling? 
It seems that you are compiling one of the older examples and not the whole OBK project. Then they don't have this function.
Just add in your main: const char *CFG_GetDeviceName() { return "SomeName"; } and that's it.
