### ISSUE TITLE
MQTT Name with some topic

### ISSUE THREAD

**Issue by PeterPolacek** [openshwprojects/OpenBK7231T_App#103]
Hi, when i  want to add some topic to mqtt message i can do it with adding topic/short_name .. but after reset device it stops sending mqtt messages at all.
Thank you

**Comment by iprak** [comment]
The MQTT logging in the web Application might be useful in this regards.

I also opted to `Broadcast self state every minute` from under Flags. The setting mentions `May cause device disconnect's, DONT USE IT YET` but I haven't noticed any disconnect.
![image](https://user-images.githubusercontent.com/6459774/182509097-f1107050-eeb2-4f24-8320-c768b74cb90f.png)

**Comment by openshwprojects** [comment]
The MQTT disconnects were fixed thanks to great effforts of @valeklubomir  and @btsimonh . MQTT is now stable.

OpenBeken now support topics with slashes as well, like "beken/kitchen/lamp1", so it's also solved.

I am closing this issue now.
