### ISSUE TITLE
New LSC Smart Mood light 3204432

### ISSUE THREAD

**Issue by snakesrules94** [openshwprojects/OpenBK7231T_App#1033]
Hi all and happy new year to the community ! 
I bought today some new smart light from action which afaik is not yet seen on the database :

![IMG_0603](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/d85396bd-1169-4e05-808a-953158c3f60a)
![IMG_0604](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/fc9ab0e3-66d9-4d9a-90da-e9bedb710083)

opening is quite easy by gently cutting the glue around the edge of the refractor and then it comes :

![IMG_0599](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/7c60961a-2054-4a0c-b2b6-3ef995a0d806)
![IMG_0598](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/e8bc2424-f1c2-4014-9e8a-ad6132d64b4f)

This time , the BK7231N is soldered directly :

![IMG_0596](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/b0e1124d-3872-415e-88d4-cd047d4ba367)
![IMG_0597](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/de9075f4-7ab1-44e4-a7ef-900ccbcc01f2)
![2024-01-14_171143_035](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/6ad7183d-1ae2-48a5-b691-2899df7f4c64)

The light is recognised in tuya app with fw 2.0.0.

I've tried to flash with TCC by using a 2.0.0 7231N strip profile but without luck ( also no way with the others 2.0.0 7231N profiles ).
It seems that  the line of 9 solder points on the back of the pcb could be connected for somes to the MCU and could be used as direct access for flashing but i have no time right now to check , i will be off for 15 days

There is also a microphone on the board as this lamp can react to music .

![IMG_0601](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/a59d58f0-54e6-464b-8dcb-b8a29c6e79da)
![IMG_0602](https://github.com/openshwprojects/OpenBK7231T_App/assets/47423016/c4ee89b5-f41b-42d2-9cfc-81a908e5b203)

Regards.

**Comment by snakesrules94** [comment]
I've tried quickly to dump the fw with the lightleak app using the differents profiles but no way. Will go deeper with this stuff when i'll be back.

**Comment by openshwprojects** [comment]
Thank you for sharing, but usually, we post our teardowns here:
https://www.elektroda.com/rtvforum/forum51.html
If you want to continue on Github, then ok, just let me know, can I repost your teardown (once it's complete - with template) to our forum?

**Comment by snakesrules94** [comment]
Hello,
Sure ! You can repost on the forum. I’ve just wrote here because i have no account yet on electroda. Will continue on that after my trip. 
rgds.

**Comment by openshwprojects** [comment]
Let me know once you get this device flashed and working. Good luck

**Comment by snakesrules94** [comment]
Hello, here are the latests news .
Lamp is now flashed and running the latest Openbeken fw.
I've made a push request to TCC for integrating the flashing profile.

template :
`{
  "vendor": "Tuya",
  "bDetailed": "0",
  "name": "Lsc Smart Mood Light",
  "model": "3204432",
  "chip": "BK7231N",
  "board": "TODO",
  "flags": "1024",
  "keywords": [
    "TODO",
    "TODO",
    "TODO"
  ],
  "pins": {
    "6": "PWM;1",
    "7": "PWM;2",
    "14": "Btn_Tgl_All;0",
    "24": "PWM;3",
    "26": "PWM;4"
  },
  "command": "",
  "image": "https://obrazki.elektroda.pl/YOUR_IMAGE.jpg",
  "wiki": "https://www.elektroda.com/rtvforum/topic_YOUR_TOPIC.html"
}`

**Comment by snakesrules94** [comment]
Final template :
`{
  "vendor": "Tuya",
  "bDetailed": "0",
  "name": "Lsc Smart Mood Light",
  "model": "3204432",
  "chip": "BK7231N",
  "board": "TODO",
  "flags": "1024",
  "keywords": [
    "TODO",
    "TODO",
    "TODO"
  ],
  "pins": {
    "6": "PWM;1",
    "7": "PWM;2",
    "14": "Btn;5",
    "24": "PWM;3",
    "26": "PWM;4"
  },
  "command": "",
  "image": "https://obrazki.elektroda.pl/YOUR_IMAGE.jpg",
  "wiki": "https://www.elektroda.com/rtvforum/topic_YOUR_TOPIC.html"
}`

Now back power button is working fine.

**Comment by openshwprojects** [comment]
It's now present here:
https://www.elektroda.com/rtvforum/topic4033331.html
Thank you, closing as solved
