### ISSUE TITLE
Set more MQTT messages

### ISSUE THREAD

**Issue by PeterPolacek** [openshwprojects/OpenBK7231T_App#104]
Hi, can i set more MQTT info messages from BK7231 ? F.e. wifi strength, ip, mac, gate etc ..
Thank you

**Comment by iprak** [comment]
I am curious about the use of such a message? Is your device mobile such that it connects to different access points?

You can get a MQTT message for ip address by setting this flag.
![image](https://user-images.githubusercontent.com/6459774/182509514-64bb7c7c-164a-4232-84c9-1ff389f6c3b8.png)

**Comment by iprak** [comment]
I think this is a neat idea. The ESP8266 [Espura ](https://github.com/xoseperez/espurna)firmware broadcasts status message for vcc, signal strength, etc. This chip does not seem to expose internal vcc but some other parameters can still be broadcasted,

**Comment by iprak** [comment]
Please check if the additional messages suit your need.

**Comment by openshwprojects** [comment]
Thanks to great help from @iprak , I think this can be closed now.
