### ISSUE TITLE
No access to constants since version 1.17.410

### ISSUE THREAD

**Issue by repsac-by** [openshwprojects/OpenBK7231T_App#1040]
When using constants of the form $CH1, no value is substituted.

**Firmware:**
- Version 1.17.410

**To Reproduce**
1. Go to Web Application
2. Click on Log
3. Send command:  echo $CH1
4. See log

https://github.com/openshwprojects/OpenBK7231T_App/compare/1.17.409...1.17.410#diff-267a898ed4fb6492fd66e5e0a5ff4f2b0585104ea84e7acbda9eac052fadae2a

**Comment by openshwprojects** [comment]
Thank you, fixed! The parser must have broken/.
