### ISSUE TITLE
CSE7766 driver?

### ISSUE THREAD

**Issue by belikh** [openshwprojects/OpenBK7231T_App#109]
Hi, is there any chance of including the power monitor IC CSE7766 driver?

I have this device: 
https://templates.blakadder.com/deta_6920HA.html

I've managed to flash the WB2S within and the touch sensors and relays are working, but I'm not sure how to proceed with adding voltage/current sensor.

It seems supported in Tasmota and ESPHome.

(for anyone interested I needed to desolder the WB2S in order to flash.)

**Comment by openshwprojects** [comment]
CSE7766 looks very simple, it uses UART interface, but I would need to get somehow one device for testing.

**Comment by belikh** [comment]
Would remote web access to my device be of any help?    Otherwise I don't mind testing it.   I'm not sure how commonly the CSE7766 is used but we don't have a lot of options in Australia.

**Comment by openshwprojects** [comment]
It would be very helpful, but I would have to have the remote access to openbk panel, I would need to be able to do a firmware update, and there would need to be some kind of load in the socket, maybe 10W bulb or something.

I would also need some photos from inside or at least know which pins are used by CSE7766

**Comment by belikh** [comment]
I'm assuming that the chip is on the 1TX and 1RX pins, as I can't flash with those connected.   

Device is at http://110.151.54.191/ at least for now.  I'm connected via LTE temporarily.

**Comment by belikh** [comment]
![20220707_115055.jpg](https://user-images.githubusercontent.com/4435491/177672970-4a4e7332-2605-44e9-88e9-71f405c6501d.jpg)

**Comment by openshwprojects** [comment]
Ok let me see, but I think w should rather get a Discord or an email conversation

**Comment by openshwprojects** [comment]
working on it

**Comment by belikh** [comment]
Aha I have awoken to find Santa visited :p

I'll leave the port open until you say you don't need it :)

I've turned off the load though until you need it (energy crisis etc)

Thanks again!

**Comment by openshwprojects** [comment]
@belikh  can you explain what exactly is inside this device, because I am not entirely sure? The power metering chip is measuring power consumption of the two sockets together?

**Comment by belikh** [comment]
Correct.  It has one input,  two power outlets and two usb sockets.   I'm not sure if it's measuring usb also.  

It's a pretty tightly packed pcb and hard to tell what's going on.

I've got another I'll take some photos

**Comment by openshwprojects** [comment]
@belikh  what is the voltage in your country, the exact measurement would be welcome...

Also, have you read that guide?
https://www.elektroda.com/rtvforum/topic3887748.html

**Comment by belikh** [comment]
![Screenshot_20220708-185813_Home Assistant.jpg](https://user-images.githubusercontent.com/4435491/177956766-03c0dfd4-6435-4b2a-b399-ea282ae5b496.jpg)

Does this help? :)

**Comment by belikh** [comment]
The insides 

![20220709_101108.jpg](https://user-images.githubusercontent.com/4435491/178083900-8b5e59a2-8d9e-4713-af3f-ef02a3c9719c.jpg)
![20220709_101151.jpg](https://user-images.githubusercontent.com/4435491/178083893-6ebb328b-48cd-4c70-8144-ceab30ea8adc.jpg)
![20220709_101312.jpg](https://user-images.githubusercontent.com/4435491/178083963-3be8d037-87b2-4f99-8c30-4fb09a40be05.jpg)
![20220709_101716.jpg](https://user-images.githubusercontent.com/4435491/178084146-dace2a02-1e49-4a6e-ae2e-9ae1ffdb888b.jpg)

**Comment by openshwprojects** [comment]
Thanks
I'll see if I get some free time today

**Comment by openshwprojects** [comment]
Can you double-check some things?

1. read this guide
https://www.elektroda.com/rtvforum/topic3887748.html
2. here is your calibration:
![image](https://user-images.githubusercontent.com/85486843/178095133-323bb717-de52-421e-b210-4ed49821d1b2.png)
3. do you also see that the Power goes to 0 with a certain delay after turning off the bulb? It's like it needs some time to notice there is no bulb
4. Do you also see that current consumption is still showing strange results even with both relays off? 
I am not sure about point 3, but point 4 can be fixed from software side by setting it to 0 when all relays are off...

**Comment by belikh** [comment]
It seems like current is behaving opposite to expectation?

(relay state at top, blue is device reading, purple meross)

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/4435491/178097973-25bb6f50-ba39-42cf-8050-2fd771296498.png">

**Comment by openshwprojects** [comment]
as the device is currently offline, can you try this and recalibrate?
https://github.com/openshwprojects/OpenBK7231T_App/commit/ce6f0aa37108b2c401c846ff876065c8acd98ff2

**Comment by openshwprojects** [comment]
I think that @talltechdude tested this code and made some good adjustments, so now I can close this issue.
