### ISSUE TITLE
Fix missing WiFi quality/rssi for ln882h

### ISSUE THREAD

**Issue by MaxineMuster** [openshwprojects/OpenBK7231T_App#1090]
**Describe the bug**
At the moment, rssi is not implemented for LN882H, so GUI for LN882H always shows 
  _Wifi RSSI: Excellent (0dBm)_
![No_rssi](https://github.com/openshwprojects/OpenBK7231T_App/assets/146550015/da8443b3-9d0e-464a-88dd-f990d93c4e42)

**Patch**
I suggest this patch to show the rssi:
![with_rssi](https://github.com/openshwprojects/OpenBK7231T_App/assets/146550015/0e511383-bddd-4e00-9698-8251d351dd49)
```

diff --git a/src/hal/ln882h/hal_wifi_ln882h.c b/src/hal/ln882h/hal_wifi_ln882h.c
index 0bee18f0..d44d32f6 100644
--- a/src/hal/ln882h/hal_wifi_ln882h.c
+++ b/src/hal/ln882h/hal_wifi_ln882h.c
@@ -131,7 +131,9 @@ void HAL_PrintNetworkInfo()
 int HAL_GetWifiStrength()
 {
     alert_log("HAL_GetWifiStrength");
-       return 0;
+    int8_t val;
+    wifi_sta_get_rssi(&val);
+    return val;
 }
 
 void HAL_WiFi_SetupStatusCallback(void (*cb)(int code))
```

**Comment by openshwprojects** [comment]
Thank you, added.
