### ISSUE TITLE
Precision of sensor reports seems lower than the internal data?

### ISSUE THREAD

**Issue by TurkeyMan** [openshwprojects/OpenBK7231T_App#1095]
**Describe the bug**
I'm noticing that the internal sensor data seems to be higher than the PUBLISH messages. Also, the rounding is always down, not towards nearest.

**Firmware:**
- Version 1.17.464
- Chip/model: BK7231N
- Device: relay + energy meter
- Relay on channel 0 + BL0942

**Additional context**
Note the difference in the values between the tele/ message and the regular updates:
```
Info: MQTT - Received PUBLISH from obk125DAED5: 180, tele/obk125DAED5/SENSOR = {"Time":"2024-02-18T05:52:22","ENERGY":{"Power": 1.312536,"ApparentPower": 1.421821,"ReactivePower": 0.546647,"Factor":0.923137,"Voltage":242.481826,"Current":0.005863,"ConsumptionTotal":25.596319,"Yesterday": 17.720535,"ConsumptionLastHour":1.312631}} (qos: 2)
Info: MQTT - Received PUBLISH from obk125DAED5: 179, obk125DAED5/voltage/get = 242.4 (qos: 2)
Info: MQTT - Received PUBLISH from obk125DAED5: 181, obk125DAED5/power/get = 1.31 (qos: 2)
```
Also note that Voltage is rounded down.

Why truncate the precision at all? I want raw data from the device, I can truncate data myself.

**Comment by openshwprojects** [comment]
That bhaviour was requested many times, so it's present in the firmware now.
Use VCPPrecision to change
https://github.com/openshwprojects/OpenBK7231T_App/blob/main/docs/commands.md

**Comment by TurkeyMan** [comment]
Thank you!
