### ISSUE TITLE
Publish some software identifying material?

### ISSUE THREAD

**Issue by TurkeyMan** [openshwprojects/OpenBK7231T_App#1101]
I want to detect/determine what software and version devices are running where possible.
There's quite a lot of device info/config that the device can report already; ie, MAC, IP, SSID, wifi channel, uptime, etc, etc.
Please also publish the software (ie, "OpenBeken"), and the version number among this device info?

**Comment by TurkeyMan** [comment]
Also the chipset would be very valuable info to report for management UI and such.
An auto-update implementation needs to know this stuff.

**Comment by TurkeyMan** [comment]
I just realised that `build` has the version, not just the build date. But the actual software name, and chipset would be good.

**Comment by divadiow** [comment]
Would LOVE to see full flash ID, size and current use/free levels. Also the module and TuyaMCU baud, if present, in the main GUI

**Comment by openshwprojects** [comment]
So you want to modify this str>
![image](https://github.com/openshwprojects/OpenBK7231T_App/assets/85486843/bd5c6af2-2e87-4b7f-80cd-cca211afacac)

**Comment by TurkeyMan** [comment]
I don't know if modify that string or add a new topic; your call on that!
Maybe a string like:
`"OpenBeken " USER_SW_VER " build: "__DATE__ " " __TIME__ " " hw: " [ie, BK7231N]`
Responding to @divadiow, maybe flash id can fit in there too? I reckon use/free levels and things like MCU baud rate might be different topic's though?

**Comment by divadiow** [comment]
Ok sure. I just like seeing all the infos. And it would be handy, especially in the case of BL602, to know if the full chip info is something like BL602C20 or C10, so people know if it's a 1 or 2mb flash when reporting on potential firmware upgrade flash size issues.

**Comment by stefan064** [comment]
Might be of some help, the home assistant discovery topic includes build verision and build platform e.g. `/homeassistant/sensor[light,swtich...]/device_full_name/config`, as Json ,e.g.:
 ```
{
  "dev": {
    "ids": [
      "OpenBK7231N_power_monitoring_plug"
    ],
    "name": "Aircon Bedroom",
    "sw": "1.17.483",                   <--------
    "mf": "Beken Corporation",
    "mdl": "BK7231N",                   <--------
    "cu": "http://192.168.0.102/index"
  },
```

**Comment by TurkeyMan** [comment]
Interesting. Thanks for the tip; although probably not really addressing this issue. I don't think we should have to rely on homeassistant discovery (which is only triggered on demand) to obtain these values.
That manufacturer string is good to know about though; I would like to see that also added to the topic that I described in the OP here.
Do devices also have a hardware embedded model number or device identifier?

**Comment by openshwprojects** [comment]
Would this change solve the issue:
https://github.com/openshwprojects/OpenBK7231T_App/pull/1107

**Comment by openshwprojects** [comment]
Ok, I think it's safe to mark it as solved and close the issue.
