### ISSUE TITLE
Can not connect to wifi

### ISSUE THREAD

**Issue by nazubi222** [openshwprojects/OpenBK7231T_App#1135]
**Describe the bug**
After i erase all flash via BK7231 GUI tool and flash the firmware. I set SSID and password to connect but it can't. I've tried change MAC and restore RF part but it sill not working. 

How can i fix this?

**Firmware:**
- Version 1.17.515
- Device: Tuya CBU 
- Chip/model: BK7231N

**Comment by rafalolb** [comment]
Additionally, I have a problem with configure secound Wifi. Second wifi not working now. This function is crucial for me.

Can you implement it if you will correct this bug?

**Comment by divadiow** [comment]
> After i erase all flash via BK7231 GUI tool and flash the firmware. I set SSID and password to connect but it can't. I've tried change MAC and restore RF part but it sill not working.
> 
> How can i fix this?`

Have you tried reflashling factory firmware then doing OBK again?

**Comment by nazubi222** [comment]
> > After i erase all flash via BK7231 GUI tool and flash the firmware. I set SSID and password to connect but it can't. I've tried change MAC and restore RF part but it sill not working.
> > How can i fix this?`
> 
> Have you tried reflashling factory firmware then doing OBK again?

I tried and it works. Thanks you
