### ISSUE TITLE
Нужна помощь с RTL8710BX

### ISSUE THREAD

**Issue by Alexej550271** [openshwprojects/OpenBK7231T_App#1165]
Доброго времени суток уважаемые разработчики! Скажите пожалуйста имеется ли поддержка чипа RTL8710BX? А то последние три приобретённые розетки на АлиЭкспресс Имеют вместо BK7213N/T чип RTL8710 и энергомонитор BL0937, а что с ним делать и как прошить вашей прошивкой не имею никакого понимания, потому прошу вашей помощи! Заранее очень вам благодарен! С уважением Алексей!

**Comment by divadiow** [comment]
OBK does not currently support any RTL chips

**Comment by openshwprojects** [comment]
Thank you for request, it's planned, but not yet available. Closing as duplicate.

**Comment by Alexej550271** [comment]
Большое спасибо, что уделили время и ответили на мой "запрос"! Надеюсь в
ближайшее время планируется добавить поддержку этих контроллеров? Очень
нужно... Так как теперь в ожидании и без дела валяются несколько розеток (((
А также позвольте пожалуйста вам предложить добавить поддержку нового и
развивающегося проекта "IotManager", это самодостаточный проект работающий
без центрального сервера, по системе сетевых сценариев через (mqtt), в
ближайшее время будет http и udp. Вся интеграция состоит только в том,
чтобы добавить ещё один, немного другой формат mqtt сообщения и возможность
принимать mqtt сообщения в "нашем формате" для управления. Все команды идут
пакетом json, с очень простым синтаксисом. У нас есть своё приложение для
мобильного телефона, а на компьютере работает через веб интерфейс. Обратите
пожалуйста внимание.

сб, 6 апр. 2024 г., 00:02 openshwprojects ***@***.***>:
