### ISSUE TITLE
BL2028N - Cannot get bus

### ISSUE THREAD

**Issue by iwjcs** [openshwprojects/OpenBK7231T_App#119]
I made the wiring to the pins as the documentation, and checked that some data from the chip were being transferred from the serial using the putty.
Unfortunatelly, when running the scripts I just receive "Cannot get bus".

This was the command issued:

python uartprogram OpenBK7231N_QIO_1.7.1.bin --unprotect -d com5 -w --startaddr 0x0
UartDownloader....
programm....
Cannot get bus. : |

**Comment by openshwprojects** [comment]
Do you know that you have to reboot the chip during the "programm...." stage so it can get bus?

Reboot by power off/on cycle or by CEN pin

**Comment by iwjcs** [comment]
Hi, thanks, actually I knew and tried it in differents ways and many times: CEN pin, config push button, power off/on. No one of these methods worked for me.
Could have an other pin to put the chip in reflash mode?
