### ISSUE TITLE
SM16703P Driver causing device hang - 1.17.566

### ISSUE THREAD

**Issue by Wolfieeewolf** [openshwprojects/OpenBK7231T_App#1237]
**Describe the bug**

The device hangs once you toggle the light. Appears to continually reboot but the lights stay on. Have seen up to 200 reboot attempts. Have to reboot into safe mode to restore.

Have tried the latest firmware 1.17.581 and the issue is still there.

**Firmware:**
- Version 1.17.566

Lots of changes to the pixel driver happened in 1.17.566

- Device - [Arlec Grid Connect Smart Desktop Bar Lights](https://www.elektroda.com/rtvforum/topic4013211.html)
- Chip/model: BK7231N
- Device config 

No pins set

Flag 4 set 

LittleFS

autoexec.bat 

```
startDriver SM16703P
SM16703P_Init 30 GRB
again:
SM16703P_SetPixel all $led_enableAll*$led_red*$led_dimmer/255 $led_enableAll*$led_green*$led_dimmer/255 $led_enableAll*$led_blue*$led_dimmer/255
SM16703P_Start
delay_s 1
goto again
```

have also tried 

```
startDriver DDP
startDriver SM16703P
SM16703P_Init 30 GRB
```

Both settings have worked on 1.17.565 with no issues.

**To Reproduce**
1. OTA to '1.17.566'
2. Click on 'Toggle 1'
4. The device hangs LEDs stay on. Have to reboot to safe mode to fix

**Comment by openshwprojects** [comment]
Thank you for reporting. Can you check if it's working with older versions? Which version broke SM16703P?

**Comment by openshwprojects** [comment]
I think you don't need that script anymore. It's now integrated into OBK without script. That's why you are getting crash...

**Comment by Wolfieeewolf** [comment]
Do I need to start the driver?

I just tried

startDriver SM16703P
SM16703P_Init 30 GRB

and it still crashes

**Comment by Wolfieeewolf** [comment]
I deleted the autoexec.bat and it appears to be working now. 

Very strange. I did try that before but nothing would light up. 

For now, it's working so I'll go ahead and close this issue
