### ISSUE TITLE
Devices hosed after OTA update to 1.10.4

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#125]
I updated 3 similar OpenBK7231T plugs from 1.4.16 to 1.10.4 (OpenBK7231T_1.10.4.rbl) and they all stopped working. 

The current version is now 1.10.7 but I can't tell from the changes if any fix was introduced in this regard.

**Comment by openshwprojects** [comment]
This sounds like a serious issue.

Did you use N chip version on T plug? It would hose them totally.

Is the safe mode working?

Can you open one device and provide log to check what goes wrong?

**Comment by iprak** [comment]
The devices were dead. I did download the hosed firmware before flashing the new one but the extracted file size does not match T or N firmware bin files. 

I think I must have flashed the wrong firmware. 

Would it be possible to show the firmware type (T/N) on config page in addition to the vesion?

**Comment by openshwprojects** [comment]
Would that be enough? Added in latest version (clear browser cache!)
![image](https://user-images.githubusercontent.com/85486843/180972234-ca793273-3098-48ea-9a2b-899fbfebf7a5.png)

**Comment by iprak** [comment]
That should help. I can see a check in OTA someday update itself pointing this mismatch.

Is that in 1.12.0 ? I am seeing empty chipset

![image](https://user-images.githubusercontent.com/6459774/180986947-78cc5708-419a-4d06-85aa-6d05e8f84a6c.png)

There was no such data piece in the response from server:
![image](https://user-images.githubusercontent.com/6459774/180987523-99122569-e473-4de1-b10a-572bdfbec047.png)

**Comment by openshwprojects** [comment]
This is because the source code of javascript panel is hosted online and the chipset request get data is in flash file, so all older flashes will return empty chipest.

Just update the flash if you need. Don't update if that's not required, it's okay to have an empty field here
