### ISSUE TITLE
BL602 AP-Mode after Flash fails

### ISSUE THREAD

**Issue by ebroecker** [openshwprojects/OpenBK7231T_App#130]
BL602 Software 1.10.4 is the last version that works.

Newer releases show up an accesspoint but after connection the device seems to hang.
no interaction with web-browser and serial console is possible.
serial console is possible after reboot.

Tested some new releases including 1.11.4.

Tested with device:
`BL602 Magic Home LED RGB IR Strip`

**Comment by openshwprojects** [comment]
thanks, should be better in 1.11.6

**Comment by ebroecker** [comment]
@openshwprojects 

Yes - thank you!
tested just 1.12.0 - seems to work again!

**Comment by openshwprojects** [comment]
Thank you for testing and sorry for the issues.

It's just it's sometimes hard to test all platforms for me.
