### ISSUE TITLE
Configuring names in the device

### ISSUE THREAD

**Issue by bilogic** [openshwprojects/OpenBK7231T_App#1384]
**Describe the bug**

# My HomeAssistant (HA)
![image](https://github.com/user-attachments/assets/961508fc-107b-4ffd-aa4d-281f9735afc0)

# My openBK device
![image](https://github.com/user-attachments/assets/2ba44fd8-9154-4b55-874f-7bedc3d28f24)

Above is a screenshot from my HA showing a connected openBK's 1, 2 and 3.
It would be great if openBK can be configured to send meaningful names instead and also show the same names on its web inteface

**Firmware:**
- Version 1.17.740
- Chip/model: BK7231N

**To Reproduce**
Shows up by default

**Screenshots**
See above

**Additional context**
No

**Comment by MaxineMuster** [comment]
I'm not sure if it's the same request, but maybe you take a look at this PR, if that might be a possible solution.
https://github.com/openshwprojects/OpenBK7231T_App/pull/1336

**Comment by bilogic** [comment]
@MaxineMuster thanks!

Yes, basically giving it a label, but I can't be certain your labels will be recognized by HA automatically, a particular way to structure the MQTT payload is required.

My view is that since these devices are rarely replaced, or changes what they control, it makes more sense to store them on the device itself. This way, if HA ever goes out of fashion, whatever else that comes along can show meaningful names when reading from MQTT.

**Comment by openshwprojects** [comment]
I think you just need to use current SetChannelLabel without any PRs and do Hass Discovery, and the names will be seen by HA...

**Comment by bilogic** [comment]
![image](https://github.com/user-attachments/assets/7a539bda-18d8-4f2c-ae1d-460ac808bfe4)


@openshwprojects thanks, HA sees the text I gave `SetChannelLabel`, but not applying them to the switches

**Comment by openshwprojects** [comment]
I think you just need to reboot... or remove and readd device via discovery (but ifirst remove)

**Comment by bilogic** [comment]
thanks it worked, I had to reboot HA.
