### ISSUE TITLE
MQTT reconnects, but entities remain disabled in HA

### ISSUE THREAD

**Issue by bilogic** [openshwprojects/OpenBK7231T_App#1388]
**Describe the bug**
After I reboot my HA, my openBK device reconnects to the MQTT, but the entities remain disabled

![image](https://github.com/user-attachments/assets/2d7ef5cf-7634-487c-839f-2b8706add5ca)

**Firmware:**
- Version [e.g. 1.14.129]
- Device? 
- Chip/model: BK7231T?
- Device config?
```
Built on Oct 5 2024 17:12:00 version 1.17.740
Online for 3 days, 4 hours, 31 minutes and 20 seconds
Device MAC: C4:82:E1:56:B8:3A
Short name: obkB00083, Chipset BK7231N
```

**To Reproduce**
1. Reboot HA
2. Go to openBK IP address
3. MQTT state is connected, but HA shows the entities as disabled

**Screenshots**
![image](https://github.com/user-attachments/assets/2639a4d3-57d7-4753-a84a-f40d273f3824)

**Additional context**
No

**Comment by bilogic** [comment]
![image](https://github.com/user-attachments/assets/51d29428-dd4b-4a35-bcb8-8a278617444e)

it's happening again

**Comment by bilogic** [comment]
I have flags 10 and 27 checkboxed, but the issue remains...

**Comment by bilogic** [comment]
I really regret flashing this instead of using tuyalocal, have to manually reboot my devices everytime HA reboots

**Comment by openshwprojects** [comment]
Do you have flag <html>
<body>

2 | [MQTT] Broadcast self state every N (def: 60) seconds (delay configurable by 'mqtt_broadcastInterval' and 'mqtt_broadcastItemsPerSec' commands)
-- | --



</body>
</html>?

**Comment by bilogic** [comment]
I did not touch that, but it is default correct? 

Can it reset itself once MQTT is disconnected so that it happens immediately after re-connection.

**Comment by bilogic** [comment]
I give up, moving to ESPHome for way better reliability.
