### ISSUE TITLE
Switch status in web app does not match config

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#144]
I have a BK7231T device with 1.12.9 firmware and am seeing the switch status displayed differently. This was happening even before 1.12.9 . The switch is actually on in this case.

![image](https://user-images.githubusercontent.com/6459774/182586711-e50a8be9-8e77-44fd-855a-1707a7c4c754.png)

**Comment by openshwprojects** [comment]
I could try looking into it, but as said earlier, the web app is here:
https://github.com/OpenBekenIOT/webapp
and was written by @btsimonh , VUE scripting is not my thing.

If anyone know VUE better, you can look at source here:
https://github.com/OpenBekenIOT/webapp/tree/gh-pages

**Comment by iprak** [comment]
Not a big deal. I am looking into the webApp.

**Comment by iprak** [comment]
Any ideas how a local website can be used to server content without tripping Cross-origin policy check?
