### ISSUE TITLE
lifespan of special Channels 200, 201, etc

### ISSUE THREAD

**Issue by PC-maniak** [openshwprojects/OpenBK7231T_App#1460]
Hi,
I would like to use one of the special channels for storing the NTP day value(int)
and update NTP only once a day - maybe every other day.. ntp is not important to update so often.. definitely not every boot - 
to shorten the online time
but how are the special channels? Can they withstand overwriting the values ​​once a day? I assume that reading the values ​​is OK.

->I have a device with a display and the time is taken care of by TyuaMCU.. it just updates from NTP for precise time

**Comment by openshwprojects** [comment]
Flash vars can be written often, they are optimized in that regard, they do like one erase cycle per 4096/64 writes (sector is 4096b and vars are 64b as far as iremember). You can also use the new direct flashvars access command:  https://github.com/openshwprojects/OpenBK7231T_App/commit/e787eecb759c02435982eec1f3be4d3b3a038fae , but remember that:
#define MAX_RETAIN_CHANNELS 12

**Comment by PC-maniak** [comment]
Thanks for the quick reply! so it's ok to use it for day tracking
