### ISSUE TITLE
SM2135 Not working correctly

### ISSUE THREAD

**Issue by hode22** [openshwprojects/OpenBK7231T_App#167]
I'm using a BK7231T tuya B22 light bulb with an SM2135 LED driver . By default the RBG configuration is wrong and CW WW is not working at all . when i tried changing the RGB channels using the SM2135_Map 0 1 2 3 4 command the light only lights white in RGB mode . Nothing else works . I thought about using in using it in the default config until the project matures a bit but unfortunately when home assistant turns on (sets a scene) the light comes on in white mode so nothing happens .

**Comment by hode22** [comment]
Hi , thanks for getting back so quick . 
I tested the SM2135_RGBCW command like you asked and i got 
1 - blue
2 - red
3 - green 
4 - nothing
5 - nothing

debug shows this
Debug:CMD:SM2135_RGBCW found chan 4 -> val255 255 (from FF)

and on SM2135_Map command at startup woud be equivvalent to FFFFFF0000 , no matter what colour i select .
![20220818_190649](https://user-images.githubusercontent.com/84182720/185464622-b6be0570-4414-4800-8fb7-d41ed540dcf3.jpg)
p

**Comment by openshwprojects** [comment]
Can you do few more tests?

SM2135_RGBCW FF00000000 - do you get full bright blue?
SM2135_RGBCW AA00000000 - do you get half bright blue?
SM2135_RGBCW 1100000000 - do you get low bright blue?

basically, does changing the hex values here makes change in dimming?


"and on SM2135_Map command at startup woud be equivvalent to FFFFFF0000 , no matter what colour i select ." this fragment I don't understand


but basically, you're saying that R G B works ok and C W never lights up?

**Comment by hode22** [comment]
Yep , dimming works . And yes C W never lights up .

**Comment by openshwprojects** [comment]
I suspect one thing, it seems there may be a certain difference between SM2153 chips...
anyway...
please wait several hours until i am at home at my main machine, I will create a test binary for you.

**Comment by openshwprojects** [comment]
update to latest version (by OTA, use correct file)
go to options general and enable this flag:
    "[SM2135] Use separate RGB/CW modes instead of writing all 5 values as RGB",
then do checks again. Are you able to lit Warm or cold white?

**Comment by hode22** [comment]
Yeaas :) the CW/WW works now :) thanks , and great job ;)
I managed to change the RBG order in HA because the SM2135_Map still doesn't work so t's all good now :)

**Comment by openshwprojects** [comment]
Hey, that's great. I happy that I helped.

Still, it's veeeeeeeery strange, because it seems there are two separate SM2135 versions and one works with your fix and second without it...

.. and now you see, projects matures a bit thanks to your testing! Is there anything you would like to see added?

**Comment by hode22** [comment]
Well , probably the SM2135 that i've got are some cheap clones or something . I got them from Tesco :P 
I don't know what I'd like to see added . this is my first BK IC that I flashed and it wasn't too bad . I'll have to get the people at my hack space to flash theirs if they have any and see what they think .
