### ISSUE TITLE
[Bug][WebUI] Missing "Return to main menu " button

### ISSUE THREAD

**Issue by pretoriano80** [openshwprojects/OpenBK7231T_App#169]
On release version 1.12.39 there's no way to return to the Main Page anymore (unless you write the correct path directly into the browser ).

Also, "Return to menu" in the Main Page is pointless because you are already there .

So i would suggest this:

- Remove  the "Return to menu" from the main page
-  Add the missing "Retur to menu" to the Config page,but  using a button instead of a link.I would name it Main Menu ,but that's just my opinion .
  
See attached screenshots:
![Screenshot_20220819_193742](https://user-images.githubusercontent.com/1435127/185667829-fb3bdf2c-41ea-462e-a92e-7c158a87ae34.jpg)
![Screenshot_20220819_193259](https://user-images.githubusercontent.com/1435127/185667835-d85136fb-fcbe-4d5f-af48-9858f733f665.jpg)
![Screenshot_20220819_193511](https://user-images.githubusercontent.com/1435127/185667837-ec056794-ef4e-42a9-807a-128b86338d80.jpg)

**Comment by pretoriano80** [comment]
it seems that it was removed by this commit -> https://github.com/openshwprojects/OpenBK7231T_App/commit/5dbbd48f3a9e84ba47325e932c4012158a2b02ad

**Comment by openshwprojects** [comment]
@iprak must have removed it by accident, it's fixed now:
https://github.com/openshwprojects/OpenBK7231T_App/commit/d8ccb05fad095db6ddca332be977284bf81cabc5
the main page now also has a "refresh" button which does not have a tgl issue

**Comment by iprak** [comment]
Yes I removed that based on the suggestion/screeshot during the discussion of this merge [here](https://github.com/openshwprojects/OpenBK7231T_App/pull/161#issuecomment-1218372225).

**Comment by openshwprojects** [comment]
Ah now I understand @iprak . It was not my intention to mark the return to menu for deletion (obviously), I was just trying to mark the "Open Web App" button and in hurry the "Return" was marked as well

**Comment by iprak** [comment]
No problem :-)
