### ISSUE TITLE
MQTT publish: support for arbitrary topic prefix without deviceid

### ISSUE THREAD

**Issue by osnwt** [openshwprojects/OpenBK7231T_App#187]
Currently publish command to topic 'topic' actually publishes it as '**deviceid/topic**'. Publishing to '/ha' actually publishes it to 'deviceid//ha' (2 slashes).

It is suggested to check if the first character of topic is '/', and if so, remove it and use the rest as an absolute MQTT topic path without device prefix. Examples:

Current behavior:
topic: '**homeassistant/device_automation**' published as '**deviceid/homeassistant/device_automation**' (with deviceid)
topic: '**/homeassistant/device_automation**' published as '**deviceid//homeassistant/device_automation**' (2 slashes)

Suggested behavior:
topic: '**homeassistant/device_automation**' published as '**deviceid/homeassistant/device_automation**' (no slash, no change)
topic: '**/homeassistant/device_automation**' published as '**homeassistant/device_automation**' (1st slash stripped)
topic: '**//homeassistant/device_automation**' published as '**/homeassistant/device_automation**' (1st slash stripped, 2nd preserved)

This feature would allow to use custom homeassistant discovery from autoexec.bat or startup command without specific support in firmware, still being compatible with the current implementation.

**Comment by iprak** [comment]
I am adding discovery support in https://github.com/openshwprojects/OpenBK7231T_App/pull/183 and it contains a new API `MQTT_Publish` which accepts topic as parameter.

**Comment by iprak** [comment]
The new `MQTT_Publish` API merged in #183 is available now.

**Comment by openshwprojects** [comment]
Thanks, I will assume it's solved now.
