### ISSUE TITLE
Leds do not turn on if I lower the brightness more than 10%

### ISSUE THREAD

**Issue by gajosu** [openshwprojects/OpenBK7231T_App#198]
Hello I just flashed a new device:
Taloya 12" 24W CCT Main and RGB Ambient Ceiling Light (GA300-24W-AI-WEMG)
https://www.amazon.com/Taloya-Ceiling-Compatible-Dimmable-Profile/dp/B07WY3VM1M

Everything works fine with the following pin configuration:

![image](https://user-images.githubusercontent.com/7597189/190061806-3182ad87-b1e9-40da-8dd9-38043a00c460.png)

the problem is that the leds do not turn on if I lower the brightness more than 10%

I just discovered this project very recently and I don't know if there is any command to correct it or something like that.

Thanks for your attention. I’m looking forward to your reply.

**Comment by openshwprojects** [comment]
Hello, thank you for trying out OpenBeken. 
Have you tried using low frequency PWM setting in Config->Configure General?

**Comment by openshwprojects** [comment]
your build seem to be from sep 11, it was added on sep 12
![image](https://user-images.githubusercontent.com/85486843/190197662-ffc9df68-f447-41a2-9245-9bb5ce3d4c48.png)

**Comment by gajosu** [comment]
works! Thank you :smile:

**Comment by openshwprojects** [comment]
Great, now I can close this issue.
