### ISSUE TITLE
BL602 LED controller flashed with OpenBL602_1.12.60.bin does not report version

### ISSUE THREAD

**Issue by deepcoder** [openshwprojects/OpenBK7231T_App#206]
Thank you for your work on this project, amazing and so useful!

I am experimenting with a couple different chips and your firmware.

I just flashed a generic LED strip controller ZJ-BWCE-RGBW V1.0 with your 1.12.60 BL602 firmware and found that it does not seem to have the version number of the firmware captured and shown, neither on web gui or via MQTT. See attach photos.

Also, the device reports -1 as rssi to MQTT.

I flashed via USB/UART using Rust blflash-flash 0.3.3 on Mac OS 12.6 host.

![bl602-no-version](https://user-images.githubusercontent.com/1409547/191393835-8b6e0eb0-5c93-4e3a-a503-bf4186ac97db.jpg)

![ZJ-BWCE-RGBW-v1 0](https://user-images.githubusercontent.com/1409547/191393861-4b0ee55e-0203-4a07-9861-3f968ecff0ab.jpg)

**Comment by openshwprojects** [comment]
Fix part 1 (default value):
https://github.com/openshwprojects/OpenBK7231T_App/commit/e7f04c6bf5f6b609a9f6c75d68122d926eaf7c24
Part 2 is on the way.

**Comment by openshwprojects** [comment]
Few months has passed but I think it's fixed now.
