### ISSUE TITLE
Webapp stopped working after update to 1.12.86

### ISSUE THREAD

**Issue by jmacato** [openshwprojects/OpenBK7231T_App#250]
As title describes.

Though there seems to be a Vue related error, this could be a clue?
![image](https://user-images.githubusercontent.com/16554748/194197141-5c3fbfbc-e7e6-477c-9843-d4a72f8d6b9e.png)

**Comment by iprak** [comment]
New devices would not cause loading `httpVuewLoader` to fail. I am not seeing any error while just navgiating to https://openbekeniot.github.io/webapp/. I am not getting any error on 1.12.84  .. maybe try clearing browser scripts.

**Comment by jmacato** [comment]
Okay... seems to be false alarm, i used my smartphone and it works there. Must've been some mishap on my laptop

**Comment by btsimonh** [comment]
check for adblockers, etc. on the laptop.  You could look at network, and see if it tried to retrieve httpvueloader?
br, 
s

**Comment by openshwprojects** [comment]
**it didn't work for me as well but now it works, was something changed?**
I obviously have an adblock
