### ISSUE TITLE
Should temperature slider appear if there are 2 PWM pins?

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#256]
This happens because of this check 
https://github.com/openshwprojects/OpenBK7231T_App/blob/34c5d1eb1ec59cd50b204660a5bffac3769e2891/src/httpserver/http_fns.c#L482

The slider doesn't seem to do anything and does not match the UI in Homeassistant.

```
		if(c_pwms == 2 || c_pwms == 5) {
			// TODO: temperature slider
			int pwmValue;
        	const char *inputName;
			const char *activeStr = "";
			if(lm == Light_Temperature) {
				activeStr = "[ACTIVE]";
			}

			inputName = "pwm";
```

**Comment by openshwprojects** [comment]
The "only 2 PWMs pins" situation was never handled by me as I never had a device with only 2 PWMs. This is not a bug, it's just 100% TODO. I only managed to handle, if I remember correctly, single PWM device, 3 PWM device (RGB) and 5 PWM device (RGBCW). 
You can do the 2 PWMs devices support if you want.

**Comment by iprak** [comment]
That makes sense .. I just happened to pick 2 PWM and started seeing color slider. Thanks for the clarification.
