### ISSUE TITLE
Should pins configured as LED appear as relay ?

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#257]
h_isChannelRelay treats LED and Relay roles alike. This later results in LED pins to appear as relay in Hass config. I suppose one would control the LED as relay which I think could be useful but this confused me for a while.

**Comment by openshwprojects** [comment]
No problems here. Some devices might have separate IO for relay and for LED. Some people might want to use onboard LED as Relay indicator, and some might want a WiFi indicator. It's assumed that you can use both Relay and LED roles on two pins in the same channel.
