### ISSUE TITLE
[solved & testing needed] realloc seems to be broken on T platform, but works on N

### ISSUE THREAD

**Issue by openshwprojects** [openshwprojects/OpenBK7231T_App#298]
I have never used realloc on OBK before, but it seems like it's broken on T platform.
realloc is used cJSON_Print, and it hangs device where realloc is called.
As a workaround, I disabled all reallocs calls in cJSON on T platform:
https://github.com/openshwprojects/OpenBK7231T_App/commit/a88140c583a4193b3659da26c1d041b3fc9c1dcb
And here I added some test console commands:
https://github.com/openshwprojects/OpenBK7231T_App/blob/main/src/cmnds/cmd_test.c
**If you're reading this, can you check on your devices the following commands:**
- testMallocFree- should work on T and N
- testRealloc- should hang on T
- testJSON - should work on T and N
**and post here results?**

Extra points for person who can figure out why realloc is broken on T, especially considering that heap4.c from RTOS seems very similar on both T and N.

**Comment by iprak** [comment]
I think I might have into something like this which is why I switched to `cJSON_PrintPreallocated`.

**Comment by iprak** [comment]
Do you know where FIX_REALLOC_ISSUE might be getting set? https://github.com/openshwprojects/OpenBK7231T/blob/eaf4e1a606571b9f13d9c933da61670c712a6c8d/platforms/bk7231t/bk7231t_os/beken378/os/mem_arch.c#L30

**Comment by openshwprojects** [comment]
@iprak , I don't know, but this is a good find. I didn't see it before. Maybe FIX_REALLOC_ISSUE is defined on N but not on T?

**Comment by iprak** [comment]
That function for N seems to be similar but there are other difference in the file itself. But still it might be worth a try.

**Comment by openshwprojects** [comment]
@iprak  os_realloc works on T, but realloc doesn't

**Comment by openshwprojects** [comment]
https://github.com/openshwprojects/OpenBK7231T_App/commit/e77d66292c0cac21226f9591b9ceb8118e973b7e

solved? still, if you can, please check

**Comment by iprak** [comment]
Confirmed: all 3 test commands pass on T.
