### ISSUE TITLE
Git conflict

### ISSUE THREAD

**Issue by valeklubomir** [openshwprojects/OpenBK7231T_App#301]
file src/driver/drv_ir.cpp is not compiled 
Debug/obj/drv_ir.cpp: No such file or directory

clean erases this file and compilation if successful, but git status report deleted file.

Extension CPP somehow is not considered as source file.

**Comment by btsimonh** [comment]
yep, working on it.
see https://github.com/openshwprojects/OpenBK7231T_App/pull/281

**Comment by btsimonh** [comment]
p.s. for local T dev, ensure to pull latest T SDK.

**Comment by valeklubomir** [comment]
I am working with N version. Don't have any T device to work with. 
Can you not rename it simple C?

**Comment by openshwprojects** [comment]
IRRemote is a C++ library. Someone needs to backport those C++-enabling changes to N:
https://github.com/openshwprojects/OpenBK7231T/commits/master
@btsimonh  might do it later?

**Comment by btsimonh** [comment]
looking at it quickly now.
@valeklubomir - I'll point you to a branch to test, may be a few minutes...

**Comment by valeklubomir** [comment]
When I delete drv_ir.cpp N build works. 
No need to hurry. I keep in mind that not to commit deletion to git.

**Comment by openshwprojects** [comment]
@valeklubomir  I am afraid that my next commit will break your compilation, unless you comment out IR line here:
![image](https://user-images.githubusercontent.com/85486843/196671440-59448322-9c11-4edc-a088-f8beba469098.png)

**Comment by valeklubomir** [comment]
Link it to T version only 
#if PLATFORM_BK7231T

**Comment by btsimonh** [comment]
@valeklubomir -
please can you test the mods in the SDK here:
https://github.com/btsimonh/tuya-iotos-embeded-sdk-wifi-ble-bk7231n/tree/AddCPPSupport

**Comment by valeklubomir** [comment]
tuya-iotos-embeded-sdk-wifi-ble-bk7231n/platforms/bk7231n/bk7231n_os/beken378/func/lwip_intf/lwip-2.1.3/port/ethernetif.c:140: undefined reference to `CFG_GetDeviceName'

**Comment by openshwprojects** [comment]
@valeklubomir  don't you need to do the same as me before, the update-submodules?

**Comment by btsimonh** [comment]
deleted from debug?  or deleted from source folder?
It could be that the stuff from the previous (bad) build in debug caused a problem...
I hate the way they have done that....

**Comment by valeklubomir** [comment]
Deleted from source directory by clean command.

**Comment by valeklubomir** [comment]
When I checkout fresh OpenBK7231T_App from git into app/OpenBK7231N_APP and execute script ./b_rebuild.sh 
It resulted with:
arm-none-eabi-gcc: error: Debug/obj/drv_ir.cpp: No such file or directory

src/driver/drv_ir.cpp is in the repositiory.

When I execute script: ./b_full.sh
which first call clean, then the build is successfully completed and binary is created.

after this src/driver/drv_ir.cpp is deleted and git status report it. With next commit file would be removed from repository.

I don't use make from App. It work only for N and T, other platforms fails, and it take time to build all of them.
At moment I work only with N versions. Do not have any other device for real testing then BK7231N

**Comment by openshwprojects** [comment]
I pushed some fixes and warning removal (not all yet).

@valeklubomir , depending whether we can resolve N build, I might make IR driver T-only so you don't have troubles compiling..

At the current state of things, the local Windows PC build works for me for T platform, while building with cygwin.

**Comment by btsimonh** [comment]
please can you check that application.mk definitely includes the line:
SRC_CPP += $(foreach dir, $(TY_SRC_DIRS), $(wildcard $(dir)/*.cpp)) 

remember, for local build, you probably have the SDK in use being outside of the OpenBeken folder:

![image](https://user-images.githubusercontent.com/3137332/196685144-1cf6b4fd-3917-4940-9ed3-e6b61212e47a.png)

NOT the SDKs inside the app folder?

**Comment by valeklubomir** [comment]
No entry in any SDK
openshwprojects/OpenBK7231T
openshwprojects/OpenBK7231N
btsimonh/tuya-iotos-embeded-sdk-wifi-ble-bk7231n/tree/AddCPPSupport

**Comment by btsimonh** [comment]
https://github.com/btsimonh/tuya-iotos-embeded-sdk-wifi-ble-bk7231n/blob/AddCPPSupport/platforms/bk7231n/bk7231n_os/application.mk

line 1106?

**Comment by valeklubomir** [comment]
Needed to checkout diffrent branch. 
Now it works correctly

**Comment by btsimonh** [comment]
we got there in the end :)  thankyou for your patience!

**Comment by valeklubomir** [comment]
@btsimonh I ment your repos.
Original I receive 
Debug/obj/drv_main.o:(.data.g_drivers+0xc4): undefined reference to DRV_IR_Init' Debug/obj/drv_main.o:(.data.g_drivers+0xc8): undefined reference to DRV_IR_RunFrame'
collect2: error: ld returned 1 exit status

**Comment by btsimonh** [comment]
I think this is WIP ref @openshwprojects - i.e. although the functions are in the drv_ir.cpp, I suspect he needs to add N platform to enable them for you too.  (look at #defines?).  Just shut down my OpenBeken dev laptop.... so can't check.

looking direct at github, the whole file has #if PLATFORM_BK7231T around it.

try:

#if PLATFORM_BK7231T || PLATFORM_BK7231N

that may work :).

**Comment by btsimonh** [comment]
or 
#if PLATFORM_BEKEN

**Comment by openshwprojects** [comment]
I was out for a 15 minutes or so, @valeklubomir  if that's a fix can you submit a pull request?

**Comment by btsimonh** [comment]
"removed #if PLATFORM_BK7231T from drv_ir.cpp"
it probably needs 
#if PLATFORM_BEKEN
else other builds may break.
