### ISSUE TITLE
SM 2135 - insufficient brightness in the channels CW

### ISSUE THREAD

**Issue by esnet146** [openshwprojects/OpenBK7231T_App#312]
Is the current set correctly for CW channels? 

in description max current 60ma
https://github.com/arendst/Sonoff-Tasmota/files/3656603/SM2135E_zh-CN_en-US_translated.pdf
OUT4 / OUT5 Output current I  60 mA

**Comment by openshwprojects** [comment]
Replied:
https://www.elektroda.com/rtvforum/viewtopic.php?p=20246171#20246171

**Comment by esnet146** [comment]
Excellent!

SM2135_Current CWcurrent RGBcurrent ( SM2135_Current 0x07 0x02 )  - Very well!
max: SM2135_Current 0x0A 0x02 - Causes extreme heat...
