### ISSUE TITLE
MQTT Aubess Smart Plug no 

### ISSUE THREAD

**Issue by daniel-hofer** [openshwprojects/OpenBK7231T_App#322]
The values for power, voltage, current have no Unit shown in my homeassistant mqtt dashboard. Is it possible to add the Unit in the mqtt-payload?
Here The example of my Aubess Plug - am I right, that the line "unit_of_measurement: V" would do the trick? 
Maybe I have to ad this in my homeassistant configuration.yaml.
device:
  identifiers:
    - Aubess_Plug_Tasmota_01
  name: Aubess Plug Tasmota 01
  sw_version: 1.14.34
  manufacturer: Beken Corporation
  model: BK7231N
  configuration_url: http://192.168.1.99/index
name: Aubess Plug Tasmota 01 current
availability_topic: obk1F279EAB/connected
unique_id: Aubess_Plug_Tasmota_01_sensor_1
qos: 1
device_class: current
state_topic: obk1F279EAB/current/get
state_class: measurement
platform: mqtt

**Comment by openshwprojects** [comment]
You can certainly display the values by hand, just like in this topic: https://www.elektroda.com/rtvforum/topic3887748.html
but the HA **discovery** should work automatically. Thoughts, @iprak  ?

**Comment by iprak** [comment]
My understanding from this wiki was that `device_class` should take care of adding the matching unit but apparently it does not.
![image](https://user-images.githubusercontent.com/6459774/197399924-44f3e8d7-b76c-4821-bc65-241d47a4ceb3.png)

I admit I only verified the icon which is more prominent. I will add units to those 3 sensors.

**Comment by iprak** [comment]
If you take the latest build and then invoke HomeAssistant Discovery, then you should start seeing units.

**Comment by daniel-hofer** [comment]
Thank you for the fix, insatlled now the latest release and can see the units now in homeassistant.
Great work, thanks a lot!
