### ISSUE TITLE
Logging is repeatedly indicating Button_OnLongPressHold

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#348]
Version 1.14.71 
Device: BK7231T

I am seeing Button_OnLongPressHold repeatedly getting logged which is both incorrect and annoying, it pushes everything else out of view very quickly. Can separate logging option be created for this and this logging probably should be off by default.

```
Info:MAIN:Time 127, idle 87752584, free 88256, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 3/38
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 128, idle 88437668, free 85184, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 3/38
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 129, idle 89127492, free 97056, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 130, idle 89817197, free 97056, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:GEN:dhcp=0 ip=192.168.1.211 gate=192.168.1.2 mask=255.255.255.0 mac=c8:47:8c:00:00:00 
Info:GEN:sta: 1, softap: 0, b/g/n
Info:GEN:sta:rssi=-60,ssid=solar,bssid=14:dd:a9:d8:01:00 ,channel=10,cipher_type:
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 131, idle 90505383, free 88272, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 3/38
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 132, idle 91189672, free 97056, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 133, idle 91882366, free 96448, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 3/38
Info:GEN:26 Button_OnLongPressHold
Info:GEN:26 Button_OnLongPressHold
Info:MQTT:MQTT deduper sent 0, culled 0
Info:NTP:Seconds since Jan 1 1900 = 3875947190
Info:NTP:Unix time  : 1666958390
Info:NTP:Local Time : 2022/10/28 11:59:50
Info:MAIN:Time 134, idle 92575308, free 97056, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 2/38
Info:GEN:26 Button_OnLongPressHold
```

**Comment by openshwprojects** [comment]
Do you have a pin role with Button? Do you press that one? Or maybe you have Button_n?

**Comment by openshwprojects** [comment]
huh it seems that change broke the buttons
https://github.com/openshwprojects/OpenBK7231T_App/commit/6ecba9344d2e4a7404d8dc90f51742c2c04e6290

**Comment by iprak** [comment]
Yes I do have a button but this recently started happening. The message is just not useful and fills up the view pretty quickly. I did filter out GEN but that makes debugging actual button click difficult. Thanks for looking into it.

**Comment by valeklubomir** [comment]
@openshwprojects  @iprak  Yes I have it tested. We had this discussion already. Your definitions of negated pin roles is not matching logic normaly used in electronics. Negated signal is low active. So when pin is grounded when button pressed this means negative logic. Inactive state in input is 1 and active state on button is 0.
Question is, Why do you have different logic for buttons and for relays. Most of the relays in this devices are switched by n-channel MOSFET. So to activate relay you apply Logic 1 as active state and for button you assume active state Logic 0.
All device with relay I select pin role "REL" and set startup value 1. Even when sending to MQTT you report 1 when relays is active. But Now I just change from "Button_n" to "Button" and the signal Button_OnLongPressHold will be resolved.

**Comment by valeklubomir** [comment]
This is the simplest explanation I found:
[https://www.sealevel.com/support/what-is-the-difference-between-positive-and-negative-logic-in-digital-io-circuits/#:~:text=%E2%80%9CWhen%20a%20circuit%20requires%20logic,referred%20to%20as%20negative%20logic.](url)

**Comment by valeklubomir** [comment]
“When a circuit requires logic 1 to operate, engineers may refer to this condition as positive logic. Thus, the more positive voltage causes the action to take place. On the other hand, if a circuit requires a logic 0 to cause action, this type circuit is referred to as negative logic.

**Comment by openshwprojects** [comment]
@valeklubomir  the shortest explanation would be that "Button" is a simple "Button" as in "a Button on Tuya device" and a relay is a simple relay, as in "a Relay on Tuya device". The code and naming was created in such a way that every user can just set "Button" and "Relay" role and get everything working.

Unfortunatelly that's the standard we're following now, so we can't just make a breaking change that far in the development. The assumption is that when users buys a "Qiachip Switch" from eBay, he sets "Relay" and "Button" roles and he is good to go.

I am open to any suggestions, but as said above, I'd prefer a non-breaking ones. We even have Youtube tutorials showing setting a "Button" (not a Button_n) role for a Qiachip switch.

**Comment by valeklubomir** [comment]
**Write this explamation to read me.** 
Because me as electrical engineer, I examined the device and found button grounding PIN when pressed and as always I presumed negative signal logic so I choose Button_n and relay was switched when 1 was applied to PIN and choose REL. When device was not working correctly then I tried to figure it out and found this bug in the logic. 
**Never Ever** would think that button signaling has opposite logic as relay signaling.

**Comment by btsimonh** [comment]
@valeklubomir -
yes I agree with your logic, but all the users choose 'button' first, as the default that will work.
It's the same in Tasmota - a button is active low.
Pain in the arse, but it is what it is, and only confuses us true hardware guys :).

**Comment by openshwprojects** [comment]
I will do my best to make it clear on readme and maybe within app, @valeklubomir . As said above, I can now fully see why your interpretation is correct, but it has never occurred to me before and neither to our users, as far as I am aware about it. Futhermore, the "_n" suffix was never meant to be interpreted as in "negative logic signaling" but just as "negated", not the negative potential but "negated default value" and we assume defaults values from Tuya.

If you can see any similar mistakes, please let me know. I wish I could catch it earlier, but right now it's too late and also I think that most users always try "button" first, they are not tech-savvy.

**Comment by valeklubomir** [comment]
After so long profesional experience I can no longer think as non-tech user. 
It is like obsession when I see something like that, the urge to fix it is unresistable. :-)

@openswprojects I have left pull request for OpenBK7231N. Can I ask you to merge it?

I made MQTT output buffer larger, because some cases device lost connection due to insufficient capacity.
Probably because of JSON generated from BL09XX, since by default disabled should not be critical.
But after a lots of days now the devices seems to be more stable.

**Comment by btsimonh** [comment]
@valeklubomir - I completely understand :).  I have my obsessions, and lucky for @openshwprojects one of them is this....

but it's OK to eventually accept that you are right, but it's not right for joe average, gloss over it and feel the glory for fixing MQTT (thankyou!!!).

we're just so happy that you are here and contributing.

**Comment by btsimonh** [comment]
(my small glory this week was reduction of thread load of serial logging...  nobody will even notice...  but I did implement IR, and that I can be proud of until everyone starts shouting about it being unreliable!).

**Comment by iprak** [comment]
This question had been lingering in my head for a while. Are the SDK for the chips targetted here not mature enough? My previous experience has been with Espressif chips which are slower but almost same memory. My custom ESP8266 based Garage door opener has been running for years now and I have had no threading/memory problems.

**Comment by valeklubomir** [comment]
ESPRESSIF chips are well documented, and support is very large, arduino, esp-idf,... 
Here we are sometimes quessing. No real documentation and I have not found other type SDK.
This takes time. But since a lot of low cost product are available from china's martkets.
Makes it worth while spending time and effort.

**Comment by openshwprojects** [comment]
@btsimonh  IR is great, but the @valeklubomir LWIP fixes are really shining now, because IR can generate lots of MQTT requests.

Ok, I think the button issue is resolved, I just need to update documentation and readme (or if someone can do it faster, please do)

@valeklubomir  merged N, but don't you need the same T? 

We had a really great progress this week, let's keep it that way. I have also added a better/test SPI flasher:
https://github.com/openshwprojects/BK7231_SPI_Flasher
and also working on scripting (DIY version, will commit it soon) and TuyaMCU power metering
https://www.elektroda.com/rtvforum/topic3928897.html

**Comment by valeklubomir** [comment]
I had not yet time to test T version. Device is not yet prepared for this project

**Comment by openshwprojects** [comment]
@valeklubomir  I apologize for taking it that long, but I updated readme according to your suggestions.
https://github.com/openshwprojects/OpenBK7231T_App/blob/main/README.md
Thanks! If you see any other issues, please report them so I can fix them.
