### ISSUE TITLE
cant publish channel value

### ISSUE THREAD

**Issue by botioni** [openshwprojects/OpenBK7231T_App#362]
alias battery_lv backlog publish sensor $CH5
publish sensor $CH5
cant publish channel value

**Comment by openshwprojects** [comment]
Hello, what kind of error are you getting? I will try to check it right away, wait.
Ah, I think I suspect what you might be saying.
There is no argument expansion here... wait...

**Comment by botioni** [comment]
no error but it publishes get=$CH5

**Comment by openshwprojects** [comment]
@botioni  I know, wait 5 minutes

**Comment by botioni** [comment]
i will check

**Comment by botioni** [comment]
working thx

**Comment by openshwprojects** [comment]
Thank you, I am closing this issue.
