### ISSUE TITLE
Limit deduper logging

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#364]
I am not sure what is the purpose of the deduper logging. I don't feel it should be part of the Info level, can it be restricted to Debug level instead?

![image](https://user-images.githubusercontent.com/6459774/198829133-14016919-ce66-444a-b159-21cf9543d2d2.png)

**Comment by openshwprojects** [comment]
yes it should be debug, will fix now

**Comment by openshwprojects** [comment]
done
