### ISSUE TITLE
drv_bp1658cj debuging help not working 

### ISSUE THREAD

**Issue by botioni** [openshwprojects/OpenBK7231T_App#368]
bp1658cj not working can we have some debuging output from driver and some respons output and cmd 
g_pin_clk and g_pin_data set from cmd command 
somthing like  bp1658cj_g_pin_clk=8 ,bp1658cj_g_pin_data=24.

**Comment by openshwprojects** [comment]
We do have logging, I think, but you need to type "logtype 7" or smth in order to display it:
![image](https://user-images.githubusercontent.com/85486843/198938734-b0944d64-6771-48d6-93dd-d7fb586e73ee.png)

**Comment by botioni** [comment]
I did but all loging is for user input not for respons  from network .
And the problem is thet is not working and I dont know why .
Can be dosent changing gpio pins or somthing else .
Wold be nice to have loging about the pins thet it uses or to set them manually and to semd direct commands to the pins

**Comment by botioni** [comment]
Can sombady report thet the driver is working ?
Did sombady test it on other devices ?

**Comment by botioni** [comment]
no clock on analyzer (i ended up buying an Cheap logic analyzer SPI i2c UART) can sombady look into the code or at last test if it is working any driver i2c comunications

**Comment by botioni** [comment]
driver working properly

**Comment by botioni** [comment]
some other bug
