### ISSUE TITLE
BK7231T on WBLC5 module High power consumption

### ISSUE THREAD

**Issue by ydac** [openshwprojects/OpenBK7231T_App#371]
Hi.

I'm extremely happy I fond this project. Open sourced, reasonably stable  and loaded with features. GREAT!
Is there any possibility to reduce power consumption of the module? It consumes approx. 100mA and chip is quite hot.
Original Tuya FW consumed apxo. 30mA .

**Comment by openshwprojects** [comment]
Thank you for reporting the issue. We are already aware about it, I have created a linked issue just few days ago:
https://github.com/openshwprojects/OpenBK7231T_App/issues/351

**Comment by openshwprojects** [comment]
Solved, just use PowerSave command (put in short startup command if required to run every time on startup)
