### ISSUE TITLE
All Devices / Configuration settings are not consistently saved

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#380]
Devices: All

It seems that one should be calling `CFG_Save_SetupTimer` or `CFG_Save_IfThereArePendingChanges` after setting configuration value but many functions are not doing that. I noticed this in `http_fn_cfg_name`. 

I will look into it.

**Comment by openshwprojects** [comment]
This is obviously a simple mistake. Just add a missing call. Great catch!

PS: We could also just call "CFG_Save_IfThereArePendingChanges" in a main, every second, loop, hm...

but we also might need to check if OTA is running, so we don't write to flash from two threads! @btsimonh

**Comment by iprak** [comment]
This was only missing at 3 spots so calling `CFG_Save_IfThereArePendingChanges` would be sufficient.
