### ISSUE TITLE
"StartDriver TestPower" - > device dead. There is indeed an issue.

### ISSUE THREAD

**Issue by openshwprojects** [openshwprojects/OpenBK7231T_App#389]
Our fellow users were right. I will be looking into it right now. Just do "startDriver TestPower" on T and you will get a crash.
![image](https://user-images.githubusercontent.com/85486843/199298271-c5cf1ed2-dc4f-44a6-8112-3e6b67f0bd51.png)
NOTE: also happens with MQTT off:
![image](https://user-images.githubusercontent.com/85486843/199299145-e6f05536-47af-412d-8a7a-5d3a25aaf9c9.png)

tested on two WB3S devices so far.

wait, did someone do a sprint %f ?

**Comment by valeklubomir** [comment]
The only sprintf (%f ) is in MQTT_PublishMain_StringFloat

**Comment by openshwprojects** [comment]
@valeklubomir i am testing a potential very crude but still working vsnprintf replacement, wait 

but in general, I just did a "testLog" command on this device and also got a crash...
![image](https://user-images.githubusercontent.com/85486843/199302405-c6c1560c-5735-43ae-95e3-0bee67143e45.png)
I know this issue for a very long time already, if you look into newleddriver.c:
![image](https://user-images.githubusercontent.com/85486843/199302595-80fe9c3e-3901-44b0-bbeb-47d2380b24ad.png)
the strange thing is that in the past I had %f issues on N and now they are on T...

but again, maybe I will know more soon, testing.

**Comment by mariusbach** [comment]
If it helps nailing it down, the issue appeared upon introduction of .106; with .105 all is fine on my end.

**Comment by openshwprojects** [comment]
**I have added a vsnprintf lightweight replacement and no longer have any crashes.** Please wait until tomorrow morning for a commit. I have to do more tests.
The lightweight vsnprintf2 is cool, very little stack usage, thread safe, etc (well maybe it relies on itoa from compiler  but still).

**Comment by openshwprojects** [comment]
Some update from me. @iprak  @valeklubomir 

As said yesterday, the "testLog" command crashes my WB3S because of %f in addLogAdv. The "startDriver testPower" also crashes my WB3S, because of HTTP printfs.

Now I have gradually replaced addLogAdv vsnprintf with a light-weight version and testLog command no longer crashes.

"startDriver testPower" was still crashing, so I replaced HTTP printf vsnprintf and now it also works again.

**So using our own lightweight vsnprintf seemingly solves all issues. The only problem now is we will miss some more advanced sprintf syntax....**

**Comment by openshwprojects** [comment]
For reference; here is the code I work with:
https://github.com/openshwprojects/OpenBK7231T_App/commit/8b844c7f78a195332365d47d9df91e7e0cb168c7
It seems to fix almost all crashes, all immediate crashes (crash on "testLog" command, crash on "startDriver TestPower", crash on publish receive), but device is still not stable for me.

the code above is not enabled, just included in App, so you can play with it.

NOTE: do not try to just replace original "sprintf" or smth with out sprintf . I tried once and it resulted in WiFI issues. That is why I prefer to use #define to override sprintf instead of a linker method.

**Comment by iprak** [comment]
What code change actually led to this issue? That can help us identify how to prevent something like this in future.

**Comment by openshwprojects** [comment]
@iprak to be honest, I am not sure. But I know for 100% that I had a "addLogAdv %f" crash really months and months ago. So the printf/sprintf/vsnprintf issue is a long term one. At least that I think may be fixed now, but NOTE: I didn't enable my sprintf etc etv vsprintf yet in the build, just submitted the code.

It is very possible that sprintf/vsnprintf %f crash is just an effect of some other problem, threading or memory, but at least code will be safer now

**Comment by iprak** [comment]
I noted that my W600 was not impacted by this, probably because all drivers are disabled for that chip or maybe the printf is just different there? Also, the 7231 where I did encounter the issue, no drivers were enabled.

I am going to put a separate idea for allowing OTA from native webApp so that one could upload firmware locally in AP mode. I was unable to downgrade the firmware and had to open the device and use uart approach . What do you think about this?

An unrelated question: Have you considered starting a Discord server for this project? We tend to use issues/comments for communicating and maybe Discord might be faster in that respect? We can still summarize our discussion into PR so that we don't lose it.

**Comment by btsimonh** [comment]
I was also suspecting sprintf a few weeks back - which led to the memtest code...
The vsnprintf function I found came from someone who obviously had problems in lwip - because it had been modified to print IPs directly from an lwip structure.  However, I never got to trust it.
Maybe write a function 'char *s getFloatStr(float f, char *s, int len)' == multiply by 1000, itoa, insert '.', and then search our code for %f and replace with %s and use the fn?
My worry about raw %f is 1/3 = 0.33333333333333333333333333333333333333333333333333333333
but we will never need more than 0.333?

**Comment by openshwprojects** [comment]
I have experienced %f addLogAdv issue for the first time many months ago. It was when I created cmd_newLedDriver.c. I have tested it only on T and it worked great with addLogAdv("%f"), but then someone got it crashing on N, and that's how I realized.
And now... %f is crashing for me on T, too. Very strange.

@iprak  it's good you're testing W600

@iprak  I really don't like Discord. It's out of our control, it's not indexable in search engines and it's messy. Elektroda is IMHO way more reliable, with somewhat more than 20 years of history, the biggest forum in Poland and I do my best to promote them to the world. Futhermore, Elektroda provides me support as well, like sending me devices for testing

Still, I see your point - can you send me your Discord on Elektroda Private Message? I think we could benefit from having a private dev-only server. We must do our  best to resolve all issues swiftly.

@btsimonh we can check that, also I have managed to get a script-only build working on windows, so I will check, wait a second

**Comment by mariusbach** [comment]
> I was unable to downgrade the firmware and had to open the device and use uart approach

@iprak What worked for me was 5x powercycle to start in AP mode and disable all drivers and MQTT (!). Then the device would find it's way back to the normal wifi network and I was able to do OTA as usual there.

**Comment by openshwprojects** [comment]
@mariusbach in my case turning off MQTT server or disabling MQTT really helps a lot and it don't crash any more. 

I pushed a win_main that is able to run SPRINTF replacement and my Scripting stuff on Windows:

https://github.com/openshwprojects/OpenBK7231T_App/commit/0b536684909dbb5f48e2ed563b1f934c1e3fc372

**Comment by mariusbach** [comment]
@openshwprojects Thanks, but MQTT is essential for me. Perhaps you could leave a note somewhere (if not done, I haven't checked), that B7231T devices should stay on version .105 for the time being. I use plugs with this chip only for energy monitoring, not much for switching at all.

**Comment by iprak** [comment]
> > I was unable to downgrade the firmware and had to open the device and use uart approach
> 
> @iprak What worked for me was 5x powercycle to start in AP mode and disable all drivers and MQTT (!). Then the device would find it's way back to the normal wifi network and I was able to do OTA as usual there.

That has not worked for me. While the device does go into AP mode, it fails to grant ip address. I have tried connecting from multiple phones with same results. I plan to view the serial log before re-flashing it.

**Comment by btsimonh** [comment]
float print issues should now be resolved....
@iprak - if you still need to discuss firmware flashing, you could open a new issue?

**Comment by iprak** [comment]
I tried but was unable to connect to the device in AP mode. I just reflashed it and it right away connected to WiFi. This is definitely not a practical approach which is why more testing and separate build should be used as public releases.
