### ISSUE TITLE
Light on/off state not remembered after reboot or power off/on

### ISSUE THREAD

**Issue by GravityRZ** [openshwprojects/OpenBK7231T_App#401]
version 1.14.121

flag12 ON (should save power state)
configure startup value -1 (should remember power state)

the RGBWW light seems to remember all of it's setting after power off/on
the powerstate however is always on when restarting or switching off/on

Light Off
restart
Light comes back ON

Light Off
power off/on
Light comes back ON

**Comment by GravityRZ** [comment]
to add some more info
this is a driver based light. maybe that is the reason it is not remembering powerstate
![image](https://user-images.githubusercontent.com/16853535/200114893-377d5669-4b78-4c41-89c3-98d6ac797133.png)

**Comment by openshwprojects** [comment]
Should be fixed now?

It was simply not implemented. Saving of the enable was missing.
