### ISSUE TITLE
Pin Roles - Switch

### ISSUE THREAD

**Issue by DJVirus1980** [openshwprojects/OpenBK7231T_App#402]
HI.
It is possible to add a switch with functionality as in tasmota in pinroles?

![image](https://user-images.githubusercontent.com/63922279/199802032-f1d81c26-3965-4358-bc78-6072057dd1fa.png)

**Comment by openshwprojects** [comment]
Option 0 - toggle - is called TglChannelOnToggle, set the channel of pin to the channel whose value you want to toggle
Option 1 - follow - is dInput, set the channel of dinput to the channel whose value you want to change
Option 2 - inverted follow - as above, it's dInput_n

**Comment by DJVirus1980** [comment]
Thanks.
