### ISSUE TITLE
MQTT message led_basecolor_rgb/get use wrong value format

### ISSUE THREAD

**Issue by rogere66** [openshwprojects/OpenBK7231T_App#408]
When using the color picker in Home Assistant the marker jumps around randomly. This is caused by bad value format of the led_basecolor_rgb/get MQTT message.

Messages:
 cmnd/RGBCW_Bulb/led_basecolor_rgb  send #ff40700000
 RGBCW_Bulb/led_basecolor_rgb/get   returns  FF4070

To temporarily get around this I had to comment out the rgb_state_topic line in yaml config.

**Comment by openshwprojects** [comment]
Are you using the old version with invalid sprintf?
Please try updating to latest one.

**Comment by rogere66** [comment]
Same problem with the very latest version, 1.14.123

**Comment by openshwprojects** [comment]
@btsimonh can you check this?

**Comment by valeklubomir** [comment]
Parser in cmd_newLEDDriver.c is capable to decode 5 components.
Function sendColorChange() return only 3 components. 
cmd_newLEDDriver.c : lines 549-613
cmd_newLEDDriver.c : lines 206-221
Function LED_SetBaseColor cointains bug. parsing is not stopped after 5 components. 
Sending 6 or more components could overwrite memory.

**Comment by openshwprojects** [comment]
@valeklubomir  nice catch with LED_SetBaseColor buffer overwrite happening after 5 components.
Apart from that, from what I understand, the led_basecolor_rgbcw should not be used and it's not used in generated templates. It's a legacy thing. We are using led_basecolor_rgb and separate temperature and dimmer topics. So sendColorChange should always send always 3 components, otherwise sendTemperatureChange is used.

**Comment by valeklubomir** [comment]
I think point is that color picker in Home Assistant sends out #ff40700000 and device return FF4070 internally in the device it is handled correctly, but probably HA is missing the last 2 components and that is probably causing issues.

**Comment by btsimonh** [comment]
does HA expect 5 always, just with the last two empty?
Do we know what TAS does?

**Comment by valeklubomir** [comment]
I found that appended 0000 on toher place
hass.c:194
![image](https://user-images.githubusercontent.com/71550793/199938986-2b4e2ee6-4d3a-4f72-88c3-d890d0480a18.png)

**Comment by valeklubomir** [comment]
And should not template for rgbcw utilize all 5 components?

**Comment by rogere66** [comment]
The problem is most likely a missing # in front of the value - HA does then not recognize the value as hex.
HA expect only 3 values. I also removed the trailing 0000 in the yaml config.

**Comment by rogere66** [comment]
Looking at the code it seems like the problem is in function sendColorChange() in cmnds/cmd_newLEDDriver.c. The snprintf() need a leading # in the format string. The same applies also to function sendFinalColor().
I don't have the SDK installed yet so have not tested this.

**Comment by openshwprojects** [comment]
I am using RGBCW lamp with HA all the time so something must have changed that you have those issues.
Here is my YAML:

```
  - platform: mqtt
    name: "Table E27 RGBCW (N)"
    unique_id: "tableE27rgbcw"
    rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
    rgb_state_topic: "obk8D38570E/led_basecolor_rgb/get"
    rgb_command_topic: "cmnd/obk8D38570E/led_basecolor_rgb"
    rgb_value_template: "{{ value[0:2]|int(base=16) }},{{ value[2:4]|int(base=16) }},{{ value[4:6]|int(base=16) }}"
    #rgb_value_template: "{{ '%02x%02x%02x'| format(red, green, blue) }}"
    command_topic: "cmnd/obk8D38570E/led_enableAll"
    state_topic: "obk8D38570E/led_enableAll/get"
    availability_topic: "obk8D38570E/connected"
    payload_on: 1
    payload_off: 0
    brightness_command_topic: "cmnd/obk8D38570E/led_dimmer"
    brightness_scale: 100
    brightness_state_topic: "obk8D38570E/led_dimmer/get"
    brightness_value_template: "{{value}}"
    color_temp_command_topic: "cmnd/obk8D38570E/led_temperature"
    color_temp_state_topic: "obk8D38570E/led_temperature/get"
    #color_temp_value_template: "{{value}}"
    retain: true
```

but I have old HA so maybe that's not the best example...

**Comment by rogere66** [comment]
Thanks, it works now with the rgb_value_template starting at first char. I also removed the leading # on the rgb_command_template (and trailing 0000).
For some reason cmnd/obk8D38570E/led_basecolor_rgb is accepted with and without a leading #.
The real issue is then that the Home Assistant Cfg example code on the web UI is wrong and need an update.

**Comment by rogere66** [comment]
The line
 brightness_state_topic: "obk8D38570E/led_dimmer/get"
is also needed in yaml, but missing in HA example code. Without it the HA color picker brightness slider will go to max when selecting a color (it use the received color code to calculate the brightness (unless optimistic: false is used)).

**Comment by iprak** [comment]
It seems that the rgb_value_template is incorrect .. perhaps it should be using values which @openshwprojects mentioned here https://www.elektroda.com/rtvforum/topic3880540.html#20044837.

**Comment by openshwprojects** [comment]
It seems that @iprak  fixed RGB value. Thanks!
