### ISSUE TITLE
Edge Toggle Switching logic

### ISSUE THREAD

**Issue by valeklubomir** [openshwprojects/OpenBK7231T_App#412]
I have installed standard light switched ON/OFF in my home and want to add some mini switch module into wiring.
![image](https://user-images.githubusercontent.com/71550793/200018543-1e0c9cd1-b09c-4854-a8e0-41d172dc55bb.png)
Is any button configuration capable to toggle relay on edge of input signal change? 
Example of usage:
Switch ON -> Relay ON
Switch OFF -> RELAY OFF
Cloud toggle -> RELAY ON
Switch ON -> Relay OFF
Switch OFF -> RELAY ON
Cloud toggle -> RELAY OFF

**Comment by openshwprojects** [comment]
"TglChannelOnToggle" was created for this purpose. It detects a change of state (with debouncing) and toggles target channel when it happens.

**Comment by valeklubomir** [comment]
Perfect thanks.
