### ISSUE TITLE
can not add BP5758D driver based light to home assistant. popup is blocking this

### ISSUE THREAD

**Issue by GravityRZ** [openshwprojects/OpenBK7231T_App#416]
when i try to add this light it will not let me.
when i add a fake relay to the light it will but then the light obviously is recognised wrong.

please remove the popup check and just let us broadcast mqtt config nno matter what config is used

![image](https://user-images.githubusercontent.com/16853535/200115581-af9eee04-ed1b-47a9-85d7-29ae91cefbaf.png)

![image](https://user-images.githubusercontent.com/16853535/200115591-8fafa6cb-6f8e-4c6c-9c82-2f876bb9bae4.png)

**Comment by openshwprojects** [comment]
You are correct. There is an obvious mistake in HA discovery.
I have fixed that:
https://github.com/openshwprojects/OpenBK7231T_App/commit/d6237fce61e19051675ca1e6f89bdda7f58b95f1
Can you check new build?
Btw @iprak please check fix.

**Comment by iprak** [comment]
Yes that fix makes sense.

**Comment by GravityRZ** [comment]
tested with build 1.14.129 and the popup is gone and discovery is working.
light however discoverd as RGBWZ instead of RGBWW by domoticz but that is another matter 
closing this one

**Comment by iprak** [comment]
Guys can you check if the color temperature layout in our device or Hass is reversed?

It seems when I select a small value
![image](https://user-images.githubusercontent.com/6459774/200119109-b7572502-5166-4584-9f54-ebd8bcb52b34.png)
it appears like this in Hass
![image](https://user-images.githubusercontent.com/6459774/200119120-4468ca90-7052-4713-87c2-762dd9cfa867.png)

The same when value is at the other way around
![image](https://user-images.githubusercontent.com/6459774/200119227-145636d8-a2a7-4a0e-8325-bbed26d3cbe2.png)
![image](https://user-images.githubusercontent.com/6459774/200119235-1bb9e382-69a3-4899-9088-ac2ed6573e46.png)

The values in Hass and device do match.

**Comment by iprak** [comment]
I moved my comment as a separate issue so that this can be closed.

**Comment by GravityRZ** [comment]
closed
