### ISSUE TITLE
Temperature sliders in HomeAssistant and webApp don't match

### ISSUE THREAD

**Issue by iprak** [openshwprojects/OpenBK7231T_App#417]
Guys can you check if the color temperature layout in our device or Hass is reversed?

It seems when I select a small value
![image](https://user-images.githubusercontent.com/6459774/200119109-b7572502-5166-4584-9f54-ebd8bcb52b34.png)
it appears like this in Hass
![image](https://user-images.githubusercontent.com/6459774/200119120-4468ca90-7052-4713-87c2-762dd9cfa867.png)

The same when value is at the other way around
![image](https://user-images.githubusercontent.com/6459774/200119227-145636d8-a2a7-4a0e-8325-bbed26d3cbe2.png)
![image](https://user-images.githubusercontent.com/6459774/200119235-1bb9e382-69a3-4899-9088-ac2ed6573e46.png)

The values in Hass and device do match.

**Comment by openshwprojects** [comment]
That's strange! Give me a minute...

**Comment by iprak** [comment]
Both the UIs are correct. 

We use Mired value which is 1,000,000/Kelvin_value.  In Kelvin lower values represents warm and higher cool and that results in inverted slider for us.

HomeAssistant uses Kelvin ( https://github.com/home-assistant/architecture/discussions/564).

I found this code related to color temperature and maybe that was prior to that change or the value got moved around:
```
// the slider control in the UI emits values
//in the range from 154-500 (defined
//in homeassistant/util/color.py as HASS_COLOR_MIN and HASS_COLOR_MAX).

#define HASS_TEMPERATURE_MIN 154
#define HASS_TEMPERATURE_MAX 500
```

MQTT integration only uses Mired value (https://www.home-assistant.io/integrations/light.mqtt/). 

Not sure if it is worth accepting Kelvin values in web and then converting it into Mired.

**Comment by openshwprojects** [comment]
I am not aware about this. Are you saying that they have changed the standard used by HA during last several months?
My HA version:  
![image](https://user-images.githubusercontent.com/85486843/200124075-90792ec7-0dd0-4f92-b506-3ceeb454ed7f.png)

**Comment by iprak** [comment]
Sorry @openshwprojects  I did not see your response while I was typing.

These are the raw values which I see in hass upon selecting a temperature
![image](https://user-images.githubusercontent.com/6459774/200125047-afb100dc-00c1-4182-b7b3-b6a5de4ad4bf.png)

![image](https://user-images.githubusercontent.com/6459774/200125061-f5b9c533-c659-43ec-9d74-84f95cc59bca.png)

```
color_temp_kelvin: 5649
color_temp: 177
```

And this is what I see in webApp and so the Mired values do match up.
![image](https://user-images.githubusercontent.com/6459774/200125100-db44333e-b804-41c6-9960-5484f9ecae1c.png)

I am at the latest version
![image](https://user-images.githubusercontent.com/6459774/200125156-35c1169e-280b-4b2f-b887-adff6c6db92d.png)

I see a fix to warm/cold reversal and then switch to Kelvin in homeassistant/util/color.py earlier this year:
![image](https://user-images.githubusercontent.com/6459774/200125337-90b00cdb-dcdf-40fe-ac54-7ea3e525c3d4.png)

**Comment by ReanuKeeves01** [comment]
@iprak @openshwprojects 

To add on to this issue, Home Assistant has adjusted this in the latest update, you can see it in the [release notes here](https://www.home-assistant.io/blog/2022/11/02/release-202211/#color-temperatures-in-kelvin)

**Comment by iprak** [comment]
I have an idea about how to make the slide match home assistant.
