### ISSUE TITLE
Sending RGBCW value on change to MQTT

### ISSUE THREAD

**Issue by Bacto** [openshwprojects/OpenBK7231T_App#423]
Hi,

Using MQTT, when I'm changing the RGBCW value of my light, I send this: `cmnd/bulb_1/led_basecolor_rgbcw <RGBCW>`.
It works great.

<img width="359" alt="MQTT example" src="https://user-images.githubusercontent.com/1188497/200130949-a54f9402-089b-4729-96bd-94b4d479485c.png">

The light then sends to MQTT its current color: `bulb_1/led_basecolor_rgb/get <RGB>`.
Unfortunately, I can't get back the CW value.

Could the light send its RGBCW value like this `bulb_1/led_basecolor_rgbcw/get <RGBCW>` ?

It would be very useful for HomeBridge, that publishes RGBCW values and ask for a topic to get lights values.

<img width="760" alt="HomeBridge configuration" src="https://user-images.githubusercontent.com/1188497/200130928-f5c86d02-6599-4542-8d6d-60c1b5a5ecbb.png">

> Note: in HomeBridge C and W are reversed but we can switch them then in HomeBridge configuration.

Best,
Adrien

**Comment by openshwprojects** [comment]
This is good idea. I can add it, it will be possible to enable it by a flag.

**Comment by openshwprojects** [comment]
@Bacto added, can you check?
https://github.com/openshwprojects/OpenBK7231T_App/commit/b08342691de3be48691982f1dde10cf921e5253c

**Comment by Bacto** [comment]
Wow so fast!
Seems to work! Thank you so much!

Would you considere to activate donation using GitHub sponsorship (besides Paypal)?
