### ISSUE TITLE
Future request button_release event 

### ISSUE THREAD

**Issue by botioni** [openshwprojects/OpenBK7231T_App#425]
Future request button_release event

**Comment by openshwprojects** [comment]
Thank you, added in:
https://github.com/openshwprojects/OpenBK7231T_App/commit/31fd8a0c1807479b87b32948a699a633918db3c9
If there is any problem, please open new issue. Wait for documentation to see how to use.

**Comment by botioni** [comment]
thx

**Comment by botioni** [comment]
tested working
