### ISSUE TITLE
Future request read mqtt topic value.

### ISSUE THREAD

**Issue by botioni** [openshwprojects/OpenBK7231T_App#429]
Future request read mqtt topic value.
somthing like Mqtt_read bec1_Ladvance/Led_dimmer Value 
and storre it to a variale thet you can use for dimming -10

**Comment by valeklubomir** [comment]
Can you provide some example, beacuse this description hard to understand.

**Comment by botioni** [comment]
subscribe to topic like bec_ladvance/Led_dimmer/get value is 50 and read it

**Comment by mariusbach** [comment]
I think he wants the openBk-device to be able to receive messages for a user-set topic and react upon them. This way the openBk-device could be notified of a controlling device and react accordingly.

**Comment by botioni** [comment]
yes exactly

**Comment by openshwprojects** [comment]
What about using aliased commands?
1. define an alias:
 alias myUniqueName backlog led_enableAll 1; led_basecolor_rgb #FF00FF ; led_dimmer 200
2. do a MQTT publish with cmnd =  "myUniqueName" ?

**Comment by openshwprojects** [comment]
This is implemented now. Even in Tasmota tyle. But also it reacts to "get".
