### ISSUE TITLE
DGR_SendRGBCW command

### ISSUE THREAD

**Issue by botioni** [openshwprojects/OpenBK7231T_App#435]
DGR_SendRGBCW command sending red green blue cool white wwhite but after restart it is inverted to RGBWC .
if you set warm whit max and you restart the led then it will start cool whit full if you set cool white when rebooted will turn on in warm white .
please make it RGBWC

**Comment by ferbulous** [comment]
Is the color still inverted even after  the remap the colors on startup?

**Comment by openshwprojects** [comment]
@ferbulous it is fixed now, there were two issues, first with DGR and second with Remap for I2C drivervs.
