### ISSUE TITLE
BK7231S - Which Platform?

### ISSUE THREAD

**Issue by jf-wm** [openshwprojects/OpenBK7231T_App#436]
I have disassembled a bulb that uses a WB2L tuya module. Unfortunately the chip itself is buried in silicon glue, therefore i can't read what the chip is label on the outside. Connecting to the module using BK7231tools using the chip_info command outputs "Connected! Chip info: BK7231S_1.0.5 / Flash ID: 00 00 00 / Protocol: BASIC_105". 
Which firmware can I use for this chip, BK7231T or BK7231N?

**Comment by openshwprojects** [comment]
WB2L is BK7231T and WB2L_M1 is BK7231N.
Please refer to Tuya docs: https://developer.tuya.com/en/docs/iot/wb2l-datasheet?id=K9duegc9bualu
