### ISSUE TITLE
Incorrect type for energy sensor class: The following entities have state class ‘measurement’ but ‘last_reset’ is missing:

### ISSUE THREAD

**Issue by otmezger** [openshwprojects/OpenBK7231T_App#444]
**Describe the bug**
Hi, I uploaded the open beken firmware on a Aubee power metering plug. All is good, and Home Assistant sees the integration correctly via MQTT:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/2758346/200566276-825090c8-f166-44c6-b12c-69e059f549e2.png">

However, when I add the "energy" sensor to the Energy dashboard of home assistant, I get the following error:

```The following entities have state class ‘measurement’ but ‘last_reset’ is missing```

<img width="384" alt="image" src="https://user-images.githubusercontent.com/2758346/200567129-3593696a-b8b3-4fcf-94d5-a0d2e428c566.png">

According to https://community.home-assistant.io/t/energy-dashboard-last-reset-missing/406733 and 
https://developers.home-assistant.io/docs/core/entity/sensor/, the sensor class should be `energy` instead of `measurement`.
Here is a quote from the forum:

> The state class for “energy” entities should be “total_increasing” 

**Firmware:**
- Version 1.14.129
- Device: Aubees power plug
- Chip/model: BK7231N
- Device config: 
<img width="592" alt="image" src="https://user-images.githubusercontent.com/2758346/200567056-e01f849a-5d1b-4cc3-9223-fb9e9d62a326.png">

**Comment by otmezger** [comment]
I found this in the code, but I'm not sure how to use `total_increasing` for the energy sensor 
https://github.com/openshwprojects/OpenBK7231T_App/blob/fb8e9f129609db475c99082d172f83ac06663756/src/httpserver/hass.c#L266

**Comment by openshwprojects** [comment]
Temporary solution might be adding sensors directly to YAML:
https://www.elektroda.com/rtvforum/topic3887748.html
In a meantime, @iprak , this is related to HA discovery, can you check this?

I will also try to check on my device later. My device was added manually by Yaml, it's a pretty old one.

**Comment by otmezger** [comment]
Update: updated the firmware to 1.15.3 and started the MQTT discovery for Home Assistant. The same still happens.

**Comment by iprak** [comment]
I will take a look.

**Comment by iprak** [comment]
The documentation calls for `device_class` to be `energy`, the `state_class` can be measurement, total or total_increasing. And that is what I am seeing. `consumption_stats` is the odd ball.

![image](https://user-images.githubusercontent.com/6459774/200728279-a2401024-e161-4f40-bb2f-d24a12529395.png)

**Comment by otmezger** [comment]
Tahnks @iprak and @openshwprojects thats very helpful. 

@iprak I can help to test. If you let me know where in the code I can change to `total_increasing`, then I can compile the code locally and flash the device. or you produce the binary and I can flash and test. just let me know.

**Comment by iprak** [comment]
Yes `total_increasing` might be more appropriate. I see the same being for another sensor generated by a Kasa switch

![image](https://user-images.githubusercontent.com/6459774/200817943-7a5930f3-f6da-4bcb-bb2e-4c00df6fbb2b.png)

The device class for energycounter can be adjusted here
![image](https://user-images.githubusercontent.com/6459774/200818006-0ea33258-dff8-4eec-b32d-1536f399916a.png)

**Comment by otmezger** [comment]
Thanks. I’ll try to rest and make a PR. 

In my home assistant, I only see energyCounter and energyCounter_last_hour. I don’t see any stats, yesterday, today and clear date. Are those not exposed. Do you know why?

**Comment by otmezger** [comment]
@iprak I'm not sure we need to set the device_class. `energy` should be just fine. what we need to change is the `state_class`. I searched in the code and found a place to set it, and made a PR.I'm trying to compile now running `make`, so it is still wip.

**Comment by otmezger** [comment]
Sorry guys, I was not able to build the project. [make](https://github.com/otmezger/OpenBK7231T_App/blob/main/Makefile) didn't finish. Any chance anyone can try to build? I can flash my device and see if the state_class is set correctly for energy. or any help compiling. I'm getting this error:


```
olmo@Olmos-MBP OpenBK7231T_App % make
/Library/Developer/CommandLineTools/usr/bin/make APP_NAME=OpenBK7231T TARGET_PLATFORM=bk7231t SDK_PATH=sdk/OpenBK7231T APPS_BUILD_PATH=../bk7231t_os build-BK7231
git submodule update --init --recursive --remote
cd sdk/OpenBK7231T/platforms/bk7231t/toolchain/../bk7231t_os && sh build.sh OpenBK7231T dev_20221110_214413 bk7231t
From build.sh, variables are:
APP_BIN_NAME=OpenBK7231T
APP_VERSION=dev_20221110_214413
TARGET_PLATFORM=bk7231t
USER_CMD=
Start Compile
system:Darwin
removing .o files from our folders, and OUR .o and .d files from Debug
find: ../../../apps/OpenBK7231T/src/hal/*.c: No such file or directory
find: ../../../apps/OpenBK7231T/src/libraries/*.c: No such file or directory
find: ../../../apps/OpenBK7231T/src/libraries/Arduino-IRremote-mod/*.c: No such file or directory
find: ../../../apps/OpenBK7231T/src/libraries/Arduino-IRremote-mod/src/*.c: No such file or directory
find: ../../../apps/OpenBK7231T/src/libraries/Arduino-IRremote-mod/src/private/*.c: No such file or directory
find: ../../../apps/OpenBK7231T/src/win32/*.c: No such file or directory
find: ../../../apps/OpenBK7231T/src/win32/stubs/lwip/apps/*.c: No such file or directory
not rm -rf ../tuya_common/src/*.o
not rm -rf ../tuya_common/src/driver/*.o
find: ../../../components: No such file or directory
not is ci build
echo prerequirement0
prerequirement0
make[3]: ../toolchain/windows/gcc-arm-none-eabi-4_9-2015q1/bin/arm-none-eabi-gcc: No such file or directory
===========================================================
make[3]: ../toolchain/windows/gcc-arm-none-eabi-4_9-2015q1/bin/arm-none-eabi-gcc: No such file or directory
make[3]: *** [beken378/app/ate_app.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [beken378/app/app_bk.o] Error 1
Build OpenBK7231T
===========================================================
echo prerequirement1
prerequirement1
mkdir -p Debug/obj
mkdir -p Debug/bin
echo prerequirement2
prerequirement2
make[2]: *** [mp] Error 2
make[1]: *** [build-BK7231] Error 2
make: *** [OpenBK7231T] Error 2
```

**Comment by iprak** [comment]
Did you just clone OpenBK7231T_App ?

**Comment by otmezger** [comment]
I tried in 2 ways:
1) using the make file in the App repo. I believe it clones the sdk repos under sdk 
2) starting from the sdk (N), and putting the App repo under app/, then running b.sh. Both fail in the same spot.

**Comment by iprak** [comment]
I can take a look at this. I think the energy entities just have to be `total_increasing`. Testing it right now.

**Comment by otmezger** [comment]
Thanks @iprak, I just tested it with the newest firmware and it works. I can now see the energy data in my energy dashboard for Home Assistant. Great work, thank you very much
