### ISSUE TITLE
Please explain what's going on with LibreTuya?

### ISSUE THREAD

**Issue by TurkeyMan** [openshwprojects/OpenBK7231T_App#463]
I just spotted this: https://docs.libretuya.ml/docs/status/supported/
I saw some youtube video about people flashing ESPHome to a BK7231N device... are there ports of ESPHome now?
Can anybody comment on the general state of these projects? What can we expect from them? Are there now multiple projects, with different devs and different goals?
Will OpenBK and ESPHome ports be competing platforms? Kinda like Tasmota/ESPHome are competing platforms now?
Importantly, can we OTA flash back and fourth between the 2 firmwares?

**Comment by openshwprojects** [comment]
Wrong repository. We do not provide support for the 3rd party projects here.
