### ISSUE TITLE
Button/WiFi led not working

### ISSUE THREAD

**Issue by valeklubomir** [openshwprojects/OpenBK7231T_App#490]
I presume since 1.15.62 button and WiFi LED does not work.
WiFI LED is not flashing.
Button does not show any log messages and no action present.

**Comment by btsimonh** [comment]
possible bugfix pushed?

**Comment by openshwprojects** [comment]
Pls fix this as well (found by doing a test run on Windows):
![image](https://user-images.githubusercontent.com/85486843/203162559-36f816ed-aaaf-48ec-a133-4bd62a3e9421.png)

**Comment by valeklubomir** [comment]
Fixed. 
Last MQTT changes also improved. Now I can run 30 msg/s.
Without PR for SDK. Reverted MQTT LWIP.

**Comment by btsimonh** [comment]
@valeklubomir - all your SDK PRs and all the other bits that I worked on too are in the next release :).
pls let us know if you see any faults in 1.15.68!

**Comment by btsimonh** [comment]
looking good N & T under heavy mqtt load :).
![image](https://user-images.githubusercontent.com/3137332/203172144-7327ed7e-cb2a-4aa7-ace0-7a7f09e38a9b.png)

**Comment by btsimonh** [comment]
maybe N serial log a bit busy during mqtt :)  something for another day...

**Comment by btsimonh** [comment]
ok, spoke a little soon.  N hung.
@valeklubomir - i'm away for a while, could you calm these:

```
mqtt_output_send: tcp_sndbuf: 14596 bytes, ringbuf_linear_available: 4, get 3625, put 3629 len 4
mqtt_pub_ack_rel_response: msg: 6 pkt_id: 7271 qos: 1
mqtt_output_send: tcp_sndbuf: 14592 bytes, ringbuf_linear_available: 4, get 3629, put 3633 len 4
mqtt_pub_ack_rel_response: msg: 6 pkt_id: 7272 qos: 1
mqtt_output_send: tcp_sndbuf: 14588 bytes, ringbuf_linear_available: 4, get 3633, put 3637 len 4
mqtt_pub_ack_rel_response: msg: 6 pkt_id: 7273 qos: 1
mqtt_output_send: tcp_sndbuf: 14584 bytes, ringbuf_linear_available: 4, get 3637, put 3641 len 4
mqtt_pub_ack_rel_response: msg: 6 pkt_id: 7274 qos: 1
mqtt_output_send: tcp_sndbuf: 14580 bytes, ringbuf_linear_available: 4, get 3641, put 3645 len 4
^ith 1
Info:MQTT:Publishing val 1 to obk0888B66E/1/get retain=0
Info:MQTT:channelSet part topic 1/set
```
particularly a corrupt char `len 144▒mqtt_`
