### ISSUE TITLE
Why do i see a lot of tasmota things in http response

### ISSUE THREAD

**Issue by GravityRZ** [openshwprojects/OpenBK7231T_App#494]
Hello,
running 1.15.70
i am using http calls in domoticz to control the light.
to do some testing i did the same command in a google chrome browser.
the response is fine but it looks like the light contains a lot of NON  OpenBK  statements regarding Tasmota, and dlink 

is this copied code which needs to be changed?

`{"Status":{"Module":0,"DeviceName":"lsclamp","FriendlyName":["lsclamp"],"Topic":"lsclamp","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"HardwareWatchdog","Uptime":"30T02:59:30","StartupUTC":"2022-10-10T16:09:41","Sleep":50,"CfgHolder":4617,"BootCount":22,"BCResetTime":"2022-01-27T16:10:56","SaveCount":1235,"SaveAddress":"F9000"},"StatusFWR":{"Version":"OpenBK7231T_1.15.70","BuildDateTime":"Nov 22 2022 06:36:43","Boot":7,"Core":"0.0","SDK":"","CpuFrequency":80,"Hardware":"BK7231T","CR":"465/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["DLINK_FastNet",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A8009","2805C80001000600003C5A0A000000000000","00000280","00006008","00004000"]},"StatusMEM":{"ProgramSize":616,"Free":384,"Heap":25,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540A1","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"tasmota-D79E2C-7724","IPAddress":"192.168.0.104","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.0.1","DNSServer2":"0.0.0.0","Mac":"10:52:1C:D7:9E:2C","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.0.113","MqttPort":1883,"MqttClientMask":"core-mosquitto","MqttClient":"core-mosquitto","MqttUser":"homeassistant","MqttCount":23,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4},"StatusTIM":{"UTC":"2022-11-09T19:09:11","Local":"2022-11-09T20:09:11","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":"+01:00","Sunrise":"07:50","Sunset":"17:17"},"StatusSNS":{"Time":"2022-11-09T19:09:11"},"StatusSTS":{"Time":"2022-11-09T20:09:11","Uptime":"30T02:59:30","UptimeSec":2602770,"Heap":25,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":23,"Dimmer":40,"Fade":"OFF","Speed":1,"LedTable":"ON","Color":"0,0,0,0,101","HSBColor":"0,1,1","Channel":[0,0,0],"CT":500,"POWER":"ON","Wifi":{"AP":1,"SSId":"SSIIIIIIIIIIIID","BSSId":"30:B5:C2:5D:70:72","Channel":11,"Mode":"11n","RSSI":78,"Signal":-61,"LinkCount":21,"Downtime":"0T06:13:34"}}}`

**Comment by openshwprojects** [comment]
Those are mostly placeholders because I was testing with Tasmota Control and Tasmota Remota and tried to make it 100% compatible, and those apps really seem to have issues if some sections are missing.
I will try to trim it down soon
