### ISSUE TITLE
Reset to defaults?

### ISSUE THREAD

**Issue by Wolfieeewolf** [openshwprojects/OpenBK7231T_App#500]
is there any way to reset a device to default settings? I have been messing around with a device and just would like to set it back to what is was when i first flashed the device. Anyone have any idea if this is possible?

**Comment by openshwprojects** [comment]
Hey, "ClearConfig" command, but it will also return device to AP mode.

**Comment by Wolfieeewolf** [comment]
Excellent! Thanks for the quick reply :)
