### ISSUE TITLE
VoltageSet "Command not found" 

### ISSUE THREAD

**Issue by ben-willmore** [openshwprojects/OpenBK7231T_App#501]
In the Command Tool, the command "VoltageSet <number>" (or CurrentSet, or PowerSet) produces the error "Command not found". However, the actual values are saved correctly.

- Version 1.15.70/1.15.78
- LSPA7 https://www.elektroda.com/rtvforum/viewtopic.php?p=20300613#20300613
- Chip/model: BK7231T

<img width="554" alt="Screenshot 2022-11-26 at 16 03 41" src="https://user-images.githubusercontent.com/956926/204098054-db26751a-1990-409a-86d7-b861f4bb1960.png">

**Comment by openshwprojects** [comment]
Thanks, it should be fixed in today or tomorrow release

**Comment by ben-willmore** [comment]
Confirming this is fixed in .90
