### ISSUE TITLE
Calibration settings not saved across restarts

### ISSUE THREAD

**Issue by ben-willmore** [openshwprojects/OpenBK7231T_App#502]
When I first tried to calibrate my devices, the VoltageSet, CurrentSet and PowerSet commands did nothing -- I got the "Command not found" error (#501) and nothing else happened. Strangely, after I set up long and short MQTT names, the commands started working correctly (though I still get the Command not found error).

* Version 1.15.70/1.15.78
* LSPA7 https://www.elektroda.com/rtvforum/viewtopic.php?p=20300613#20300613
* Chip/model: BK7231T

**Comment by openshwprojects** [comment]
I think you've found two issues - one is a bug that makes "Command not found" print while command is executed, and second is not a bug, but... but commands started working correctly because the driver for BL0937 starts after reboot and most likely you have rebooted?
Wait, I will fix the "command not found" first

**Comment by ben-willmore** [comment]
I don't think it's about the BL0937 driver being loaded -- it seems like it always gets loaded automatically. I'm testing now with 1.15.90, and VoltageSet now works if I have `startDriver BL0937` as a Startup Command. If I set the Startup Command to blank and reboot, the BL0937 driver is still loaded, and VoltageSet still works.

**Comment by openshwprojects** [comment]
@ben-willmore this is because, if on startup, you have BL0937 pins set, it will start automatically.

If you set pins for BL0937, but don't restart, then driver is not started yet.

This is why for the first time, just once, you get "unknown commands"

**Comment by ben-willmore** [comment]
OK, makes sense. I couldn't reproduce this on a cleared device, so I will close this.

**Comment by ben-willmore** [comment]
I went through this again with my other plugs (same model), after upgrading to 1.15.90. Now, VoltageSet works, but the value is not saved across reboots. 

1. Check voltage in main page -- 242V
<img width="958" alt="Screenshot 2022-11-27 at 16 52 39" src="https://user-images.githubusercontent.com/956926/204150324-5a98284c-5e42-4283-bba2-de8e48d15d60.png">

2. Calibrate voltage to 100V
<img width="873" alt="Screenshot 2022-11-27 at 16 52 58" src="https://user-images.githubusercontent.com/956926/204150322-c8d9d40f-81d5-41cf-928c-5ce844c0da1f.png">

3. Check voltage again -- it's correctly changed to 100V
<img width="965" alt="Screenshot 2022-11-27 at 16 53 15" src="https://user-images.githubusercontent.com/956926/204150321-288cdf36-1a0e-40f0-bf4c-d5dae5ffe4b9.png">

4. Reboot the device and check voltage again -- it's back to 240V
<img width="952" alt="Screenshot 2022-11-27 at 16 54 00" src="https://user-images.githubusercontent.com/956926/204150317-ad4f6f1e-2b6b-4afc-a016-e7915b7a67e6.png">

I cleared the configuration on this device and set it up as new, and got the same result.

**Comment by ben-willmore** [comment]
I worked out why this seemed intermittent to me. If I hit "Restart" in the GUI after running VoltageSet, then the value is correctly saved, and I can then cut power to the device and it will restart with the correct calibration. However, if I cut power to the device straight after VoltageSet, the calibration is lost when the device restarts.

**Comment by openshwprojects** [comment]
ah, now I sese what you mean, thanks. There was an obvious bug, the save flush was missing for VoltageSet etc but flush was happening if you changed something else later so people didn't notice, most of the time...
https://github.com/openshwprojects/OpenBK7231T_App/commit/90f68934fa300d524e8549713d5f7d1bbe976f25
next release should have it fixed

**Comment by ben-willmore** [comment]
So quick, thanks!

**Comment by openshwprojects** [comment]
If there are any other strange issues, let me know
