### ISSUE TITLE
channelSet fails if topic has '/'

### ISSUE THREAD

**Issue by no2chem** [openshwprojects/OpenBK7231T_App#515]
**Describe the bug**
I like to name my topics with a / to organize. 

For example, I like to set a name of 'openbk/christmas_tree_lights' for christmas tree lights, etc, so it's easier to navigate my MQTT tree.

It seems like the channel parsing of the code erroneously stops at the first '/'. So this would result in channelSet parsing '-1' when I call openbk/christmas_tree_lights/1/set=1 .

Glancing at the code, it looks like the issue is in `int channelSet(obk_mqtt_request_t* request) {`. 

I'll try to submit a PR soon.

**Firmware:**
- Version [e.g. 1.14.129]
1.15.130
- Device? 
Generic Tuya Plug
- Chip/model: BK7231T?
BK7231N
- Device config?
N/A

**To Reproduce**

Set client name with a '/'. e.g. 'openbk/light_xmas_tree'

Try publishing a message to turn on the relay. e.g. 'openbk/light_xmas_tree/1/set'

(failure) relay doesn't turn on (expected) relay turns on

** relevant logs **
```
Info:MQTT:MQTT client in mqtt_incoming_publish_cb topic openbk/light_xmas_tree/1/set
Info:MQTT:MQTT in topic openbk/light_xmas_tree/1/set
Info:MQTT:channelSet part topic light_xmas_tree/1/set
Info:MQTT:channelSet channel -1
```

**Comment by openshwprojects** [comment]
I have never tried setting such device name. There indeed might be an issue.

Would you like me to help, or should I wait for your PR?

**Comment by no2chem** [comment]
I'm trying to setup the build toolchain, admittedly its taking me awhile. I can send the PR, it's just a minor fix but I haven't tested it. I'll do that now.

**Comment by openshwprojects** [comment]
@no2chem  was it tested on your device? I will try to check it in practise today, but it looks ok

**Comment by no2chem** [comment]
i'm testing it at the moment, there's a bug so standby :)

**Comment by no2chem** [comment]
@openshwprojects fixed, please take a look at latest push
