### ISSUE TITLE
W600 LSPA9 version with BL0937 energy metering

### ISSUE THREAD

**Issue by openshwprojects** [openshwprojects/OpenBK7231T_App#519]
According to this user, there is a such plug:
https://www.elektroda.com/rtvforum/viewtopic.php?p=20319760#20319760

Anyone here up to improving W600 support? @iprak  ? Remember last state, etc, etc?

**Comment by iprak** [comment]
I can look into preserving the last state. Perhaps driver support could be enabled one by one as such devices are encountered.

**Comment by Tryfos** [comment]
> According to this user, there is a such plug: https://www.elektroda.com/rtvforum/viewtopic.php?p=20319760#20319760
> 
> Anyone here up to improving W600 support? @iprak ? Remember last state, etc, etc?

There is also another (version of a) smart plug with W600 and BL0937, as I mention here https://www.elektroda.com/rtvforum/viewtopic.php?p=20337835#20337835   (Girier 16A JR-PM01). It comes with a C2BS chip too.

**Comment by openshwprojects** [comment]
According to report of Elektroa user, it works now.
