### ISSUE TITLE
Home Assistant auto-discovery, like ESPHome?

### ISSUE THREAD

**Issue by TurkeyMan** [openshwprojects/OpenBK7231T_App#523]
Just wondering, does OpenBeken have the Home Assistant auto-discovery using the HA protocol like ESPHome does? It's much simpler than MQTT.

**Comment by davygravy** [comment]
This is already present. 

In the webif of your flashed smart plug/device:  Config > Home Assistant Configuration > Start Home Assistant Discovery

After these button presses, my devices appeared automatically in my MQTT integration in HA. I didn’t have to touch my HA configuration.yaml file, and the whole process was essentially effortless.

**Comment by euro2** [comment]
does this give any benefits in regards to visibility in HA? When i reboot HA i have to manually toggle all openbeken's once to get HA to know the status of them

**Comment by openshwprojects** [comment]
@euro2 enable "broadcast self state every minute" or try something like retain?

**Comment by openshwprojects** [comment]
@iprak  is doing great things with autodiscovery, this is getting very advanced

**Comment by rojoricardo** [comment]
Hi, my autodiscovery for home assistant is not working, any ideas? I can see my device in MQTT Explorer, but home assistant is not auto discovering it... I really dont know whats going on
