### ISSUE TITLE
"tuya convert" for OpenBeken?

### ISSUE THREAD

**Issue by anno73** [openshwprojects/OpenBK7231T_App#531]
Hi!

I have not seen this mentioned yet anywhere, so, do you plan to have a similar tool like tuya convert for tasmota on ESPs? 
As you might know, there are a lot of cheap but nice smart plugs with power metering out there which are quite hard to open without harming the case, so traditional flashing is not an option really.

Thanks, A.

**Comment by openshwprojects** [comment]
There is a tuya-cloudcutter . This should answer your question well.
