### ISSUE TITLE
Led brightness/expo mode default value?

### ISSUE THREAD

**Issue by openshwprojects** [openshwprojects/OpenBK7231T_App#541]
After merging in https://github.com/openshwprojects/OpenBK7231T_App/pull/539 ,
_/* exponential mode command handler, usage: led_expoMode <0|1|2|3|4>
   exponential modes: 0 = Off
					  1 = 1% min brightness with moderate exponential
					  2 = 1% min brightness with full exponential
					  3 = 0.1% min brightness with moderate exponential
					  4 = 0.1% min brightness with full exponential
*/_
I think we should choose a default value for brightness mode on all devices.

Can you guys check which one in your opinion gives best results? 
Currently, the default value is 0 = Off

**Comment by WiredLife** [comment]
https://github.com/openshwprojects/OpenBK7231T_App/issues/546

**Comment by WiredLife** [comment]
I updated to current firmware and the expo mode doesnt work as i thought, tried all settings. With https://github.com/openshwprojects/OpenBK7231T_App/pull/447 i can go very down with the brightness.
With the expo mode not.
Very sad

**Comment by openshwprojects** [comment]
@WiredLife You have convinced me. We're merging #447 soon. I will allow float values for PWMs. I am closing this issue now, let's continue discussion in #447 .
