### ISSUE TITLE
MQTT initial reported IP address not updated

### ISSUE THREAD

**Issue by NielsPiersma** [openshwprojects/OpenBK7231T_App#561]
**Describe the bug**
After running "Start Home Assistant Discovery" the CURRENT IP address is reported to HomeAssistant.
When the IP address changes, this is not reported to HomeAssistant. The change can be on the same or any other subnet.

**Firmware:**
- Version [e.g. 1.15.188 to 233/latest]
- Device LSC Smart Plug
- Chip/model: BK7231T
- Device config: n/a/

**To Reproduce**
Goto home assistant configuration
Run start home assistant discovery
move to a different subnet, but keep using the same HA server
Check home assistant MQTT device and see the ip address reported in the status page.

**Additional context**
Quick fix is deleting the device from HA and restarting HomeAssistant Discovery.

Niels

**Comment by openshwprojects** [comment]
Thanks. I think you are indeed correct. IP is broadcasted on MQTT connect and not later. If it changes during runtime, it can indeed not be broadcasted to MQTT again.

I will look into it, I will also broadcast IP when it changes.

**Comment by openshwprojects** [comment]
@NielsPiersma , I have added a fix, but I don't have dynamic IPs - I am using DHCP reservation for MAC.
Can you check if it works for you?
https://github.com/openshwprojects/OpenBK7231T_App/commit/adcf2ef0016b9fc5f00bb3a506d03c5281b9fcb4
It basically checks IP every frame and if it changes, it does MQTT Ip broadcast.
Thanks!

**Comment by NielsPiersma** [comment]
Afternoon,

 

Not working as expected at this moment. I flashed device but only after starting the MQTT Discovery the ip addres was updated (to .99)

 

So I retested.

 

Current IP: 10.4.15.99 (from device)



 

In home assistant:



 

I updated the dhcp reservation, invalidating 10.4.15.99, so it must get a different IP address;

 



Now we have 10.4.15.102.

 

And over to HomeAssistant

 



 

Still stuck at 15.99

 

Re-run discovery from the device:



 

 

And updated in HomeAssistant…

 



 

Can we trigger an update / rediscovery? Or maybe do it on some kind of regular basis?

 

Niels

**Comment by NielsPiersma** [comment]
I think all my pictures were dropped ;(.

Any way,
![image](https://user-images.githubusercontent.com/70269175/209560864-52a1b9eb-cb34-4362-942f-fea340a1affb.png)
Also MQTT explorer gives it away... After the re discovery it is updated towards HomeAssistenant.

NIels

**Comment by openshwprojects** [comment]
The current modification just does the publish at "IP" topic of MQTT when IP changes, are we referring to the same thing? 
@iprak  what do you think? It looks like related to HA discovery

**Comment by NielsPiersma** [comment]
Hi,

When I do a publishall it updates the ip address. So I am considering adding it to autoexec.

Niels

**Comment by NielsPiersma** [comment]
I think it indeed does publish the change when powered on, but not when the device is restarted, and has a new IP address is assigned.

Maybe the behaviour is different between a lease renew when powered on vs renew during startup.

I’ll investigate this by changing the lease time to a few minutes and see if the lease is update without restarting the unit.

 

I’ll also check if the publishall in the autoexec resolves the issue.

 

Thanks 

 

Niels

**Comment by NielsPiersma** [comment]
Okay,
Tested, but still not working (in HomeAssistant). However, it may be related to HomeAssistant and not to OpenBeken.
Well the packet trace from the DHCP server. As you can see after a few NAK's for 10.4.15.102 it does an ACK on the 10.4.15.99.
![image](https://user-images.githubusercontent.com/70269175/209567588-61463b24-82aa-47e1-aa9b-ae2252e3b4d3.png)

And when looking into MQTT Explorer it has updated as well.
![image](https://user-images.githubusercontent.com/70269175/209567632-1abd483e-d352-4b2c-bf1e-2a78064aca19.png)

But in HomeAssistant is still is using the "old" address.

![image](https://user-images.githubusercontent.com/70269175/209567778-49c9ec5f-bda2-4675-bd3d-57b49bf62a82.png)

Keep in mind that switching from inside HomeAssistant is working fine, it is just the IP address stored in the configuration.

After executing the custom command "publishall" from the device 

![image](https://user-images.githubusercontent.com/70269175/209567915-a619d142-2c26-4e7f-8212-3e3bbe6d7219.png)


We see the data isn't updated in HomeAssistant as well. Still the former IP address;

![image](https://user-images.githubusercontent.com/70269175/209568027-fe2905d2-46f6-4c08-9f5f-46f80928b09a.png)

After a reboot, still no update of the IP address in HomeAssistant.

However, when deleting the device from HomeAssistant and executing Start HomeAssistant Discovery, it is reported with the correct IP address.
![image](https://user-images.githubusercontent.com/70269175/209568258-1cf04fc2-a694-4306-913f-a7dce0bb1c15.png)

Based on this testing IP changes during operation and after a reboot are currently not reported back into HomeAssistant.

I can do more testing if needed.

Niels

**Comment by openshwprojects** [comment]
I am starting to think that the HA is not listening to the IP publish and the thing I added does not relate to your request.

You are referring to the AutoDiscovery, which is done just once, and also might contain IP.

I must ask @iprak  about it.

PS: If you listen to MQTT publishes done by that device, when a DHCP changes IP, does it publish the new IP?  I bet it does, it's just that's not what you're asking for.

**Comment by NielsPiersma** [comment]
@openshwprojects ,
"PS: If you listen to MQTT publishes done by that device, when a DHCP changes IP, does it publish the new IP? I bet it does; it's just that's not what you're asking for."

I fully agree with your bet; I assume the IP address **is** updated. MQTTExplorer does report the new address instantly.
![image](https://user-images.githubusercontent.com/70269175/209568729-3ed268ea-c5ff-46de-b5c7-886d2b255b81.png)
 
Likely there is something else published to HomeAssistant, (initially) that needs to be updated. My tasmota's are not running MQTT anymore, but as a native tasmota device, I can't test MQTT. I'll look for another MQTT device and see if we have the same behavior.

**Comment by iprak** [comment]
HA discovery is manually invoked.

So if the ip address changes, then `Device Info`  will continue to show previous address. The HA integration if through MQTT so the integration should still work. Unfortunately, the entire discovery package has to be sent to correct this. We could try re-invoking discovery on startup and on ip-address change.

**Comment by openshwprojects** [comment]
We already have ability to call AutoDiscovery from console command, maybe just schedule autodiscovery when IP changes?

But not all of people are using that... and it might not be desirable by default?

**Comment by NielsPiersma** [comment]
I can confirm @iprak device info statement. The IP address is published to 
***homeassistant/switch/OpenBK7231T_BF512F1E_relay_1/config***
![image](https://user-images.githubusercontent.com/70269175/209570070-90c5c449-d961-49a7-95a5-438ea43e765e.png)

So that needs updating when the IP addresses changes.

NIels

**Comment by openshwprojects** [comment]
@NielsPiersma  maybe adding an event for IP change would help? Then, in autoexec.bat, you could script the AutoDiscovery to happen again automatically...

but I am not sure if such user-scriptable solution is suitable here.

**Comment by NielsPiersma** [comment]
> We already have ability to call AutoDiscovery from console command, maybe just schedule autodiscovery when IP changes?
> 
> But not all of people are using that... and it might not be desirable by default?

When doing ipv6 the only realistic option is dhcp... Sooner or later something that is likely needed.
NIels

**Comment by NielsPiersma** [comment]
> @NielsPiersma maybe adding an event for IP change would help? Then, in autoexec.bat, you could script the AutoDiscovery to happen again automatically...
> 
> but I am not sure if such user-scriptable solution is suitable here.

For me, that is fine for now. I understand where the issue is. 

But changing IP addresses is not something unheard of ;)
NIels

**Comment by NielsPiersma** [comment]
@iprak how can I do AutoDiscovery from the command line?
And would it be possible triggering it from HTTP://x.y.x./?cmnd+..... and as a MQTT cmnd topic payload?

I know many requests :) but I am managing over 1000 Tasmota devices and provisioning is the only wat managing them in a controlled way.
NIels

**Comment by iprak** [comment]
Can I ask, what are you using the url in Device Config for? I would have expected that addresses to be provisioned in such a large setup based on mac address.

**Comment by NielsPiersma** [comment]
This is how we mass reconfigure initial hosts in AP mode. We used tuya cloud-cutter and scripted the process. 
http://192.168.4.1/cm?cmnd=backlog+SetPinRole%206%20LED_n;SetPinChannel%206,1;SetPinRole%207%20Btn;SetPinChannel%207,1;SetPinRole%208%20Rel;SetPinChannel%208,1;SetPinRole%2026%20wifiled;SetPinChannel%2026,0;SSID1%20[wifissid];Password1%20[wifipwd];MqttUser%20[mqttuser];MqttPassword%20[mqtt-pwd];MqttHost%20[ip of ha];restart

Niels

**Comment by iprak** [comment]
I wonder if more sustainable solution might be look into the router settings. DHCP usually assigns the same ipaddress for a previously connected mac but the behavior is not consistent across DHCP implementations. 

But triggering `scheduleHADiscovery` should also work although you need to build some process to trigger it via listening to MQTT message.

**Comment by openshwprojects** [comment]
i have added IPChange event (with argument 0 - it's just a stub for syntax). The event is cast when IP changes. 

**addEventHandler IPChange 0 scheduleHADiscovery**

**Comment by openshwprojects** [comment]
Any news on this? @NielsPiersma

**Comment by NielsPiersma** [comment]
Sorry recovering from flu
________________________________
Van: openshwprojects ***@***.***>
Verzonden: Thursday, December 29, 2022 10:56:22 AM
Aan: openshwprojects/OpenBK7231T_App ***@***.***>
CC: NielsPiersma ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [openshwprojects/OpenBK7231T_App] MQTT initial reported IP address not updated (Issue #561)


Any news on this? @NielsPiersma<https://github.com/NielsPiersma>

**Comment by NielsPiersma** [comment]
@iprak , I am testing now, just to confirm, do I need to add 'addEventHandler IPChange 0 scheduleHADiscovery" somewhere (as a startup command?) Or is it enabled by default?

Just flashed version 268, will try now without any changes.

NIels

**Comment by NielsPiersma** [comment]
Evening @iprak 
I am starting with OpenBK firmware 268. I just updated to this version and did not (yet) issue an MQTT rediscovery from OpenBK.
 
![image](https://user-images.githubusercontent.com/70269175/210180947-a0c07ecd-c0db-4ee0-a5f6-eb523deac8db.png)

@ipark, adding the current IP address on the about page would be helpful. If needed, I can open a new change request for that.

Current IP Registration in DHCP server (free lease, not pinned/reserved)
 
![image](https://user-images.githubusercontent.com/70269175/210180968-80f39b2f-7fee-4905-9b9e-7c79d47a3ec7.png)

And HomeAssistants’ view on things.
![image](https://user-images.githubusercontent.com/70269175/210180975-0c848806-104e-4fa7-bf48-6977f810f461.png)
 
As you can see, it nicely points to the correct, current IP address; also, notice that the firmware revision is not updated either; it reports version 230 and not the just flashed 268. @iprak, can we do a rediscovery as well after a firmware update?
Now I’ll invalidate the IP address and reboot the unit, so OpenBK needs to acquire a different address.

![image](https://user-images.githubusercontent.com/70269175/210181030-c43936c2-2691-4e83-86b4-41a6fb2d15bd.png)
Reservation with a different MAC address 😊

Now reboot the plug and see the results.

We’ve migrated to 10.4.15.102
 
![image](https://user-images.githubusercontent.com/70269175/210181042-ac63b9ed-3877-4b0c-9127-6cd861e858f7.png)

Let’s see HomeAssistant:
 
![image](https://user-images.githubusercontent.com/70269175/210181043-4181cde0-d95b-482f-8488-284f4861858c.png)

No change; still has the old firmware version and the old IP address.

Executed the custom command; "addEventHandler IPChange 0 scheduleHADiscovery"
![image](https://user-images.githubusercontent.com/70269175/210181092-3b410fd1-57b0-42ec-81f8-2d2e7e18755f.png)

 
First, updated HA with the new information by starting HA discovery:
HA information after triggering HA rediscovery:
 
![image](https://user-images.githubusercontent.com/70269175/210181104-739faf2c-f234-4b68-b80a-2a59355c64c2.png)

As before, after manually running HA rediscovery, the information in HA is correct.

Now triggered, another IP change by forcing 10.4.15.99 to this mac address.
 
![image](https://user-images.githubusercontent.com/70269175/210181112-f1b89476-5d65-441f-b7b2-46231326a548.png)

I am rebooting again to see if HA rediscovery is triggered.
 
![image](https://user-images.githubusercontent.com/70269175/210181116-c5c8e995-502b-4416-970a-6bf46c11ac38.png)

And back she is.
Now see if HA is updated.
 
![image](https://user-images.githubusercontent.com/70269175/210181122-538746a2-f92a-489c-8a3a-c09283c230aa.png)

Nope, also after 3 minutes still the same. 
Maybe “addEventHandler IPChange 0 scheduleHADiscovery” only works when IP is changes during running operation and not during boot.

I think it would be a good idea to issue an MQTT rediscover on regular basis making sure the information in MQTT is accurate.

Hopefully you can help out resolving the issue

Niels

**Comment by iprak** [comment]
Using "Execute custom command" will just run that for that session, try setting the same as the "Startup command".

**Comment by NielsPiersma** [comment]
@iprak ,
Yes, I'll give that a shot.

Niels

**Comment by NielsPiersma** [comment]
I can confirm putting scheduleHADiscovery 10 as a startup command resolves the issue as expected.
Kudos!
Niels
