### ISSUE TITLE
Color mismatch

### ISSUE THREAD

**Issue by WiredLife** [openshwprojects/OpenBK7231T_App#567]
As described by others too, there is a big color mismatch.
It makes no difference if the color is transmitted with high or low brightness or as rgb or hsb.
Only the outer ring on the color wheel match.
If i set the saturation on webif of openbk higher, there is the possibility that the color match.
Looks to me its a saturation problem.
![Screenshot_20221212-021000_openHAB](https://user-images.githubusercontent.com/1356847/209710285-a8aa5e19-e20e-4d4d-b101-ae3b48c1a9ae.jpg)

**Comment by openshwprojects** [comment]
Have you tried that new exponential colour mode?

**Comment by WiredLife** [comment]
Exponential color mode?
I knew the brightness thing.
Where can i enable the color expo?

**Comment by openshwprojects** [comment]
Sorry, I meant brightness. Have you tried all the options?

**Comment by WiredLife** [comment]
Yes tried all. As i said, it looks like the saturation is the problem

**Comment by WiredLife** [comment]
https://github.com/openshwprojects/OpenBK7231T_App/pull/447
finally fixed it

**Comment by openshwprojects** [comment]
You have convinced me. We're merging #447 soon. I will allow float values for PWMs. I am closing this issue now, let's continue discussion in #447 .
