### ISSUE TITLE
Feature Suggestion: Add "All Select" & "All Clear" check box to WebApp Log view

### ISSUE THREAD

**Issue by jkwim** [openshwprojects/OpenBK7231T_App#568]
It would be good if "All Select" & "All Clear" checkboxes can be added to WebApp Log View -> Log Features.

![image](https://user-images.githubusercontent.com/84637540/209904131-48aa7ffb-ef9e-4153-b0dc-2b118abd96f9.png)

**Comment by openshwprojects** [comment]
Thank you for suggestion, added, can you check?
https://github.com/OpenBekenIOT/webapp/commit/85a904c0d36018fb8e3f111fdd2715af2c660363

**Comment by LuisThe0ne** [comment]
I think the functionality you're looking for has now been added.
(Please close this issue)

**Comment by jkwim** [comment]
Tested and working:

![image](https://user-images.githubusercontent.com/84637540/210124775-1296b6ed-e372-467b-85ba-3b1b0a6f446f.png)
