### ISSUE TITLE
Feature Request - MQTT Toggle

### ISSUE THREAD

**Issue by bgardner46** [openshwprojects/OpenBK7231T_App#573]
I use a gui that toggles an output. Until now all of my devices have been flashed with Tasmota and toggle works as an MQTT paylad. It seems like the only payload supported in OpenBK is either 1 or 0. I would like to use for example:

ktchen_light/1/set toggle

Is this currently possible or can it be added?

Thanks.

**Comment by openshwprojects** [comment]
Hello, have you tried Tasmota syntax, which is supported?

cmnd/obkDevice/POWER with payload "toggle"
(if multiple relays are present, use POWERX where X is a number)

**Comment by bgardner46** [comment]
I have not - didn't realize that the Tasmota syntax was supported. At the
moment I have utilized some programming in my home control system to
accomplish the same thing but I will definitely give it a try tomorrow.

Thanks for the quick reply

Bob

**Comment by bgardner46** [comment]
I couldn't wait. I just tried this and it worked perfectly. The more I learn, the more I like this project.

Thank you.

Bob

**Comment by openshwprojects** [comment]
Thank you, is there anything else I can help you with?
