### ISSUE TITLE
MQTT Group Topics

### ISSUE THREAD

**Issue by NielsPiersma** [openshwprojects/OpenBK7231T_App#576]
I would need MQTT Group Topics to work for provisioning and configuration purposes.
In Tastmota we use "cmnd/tasmotas/"
![image](https://user-images.githubusercontent.com/70269175/210183310-8490e998-bc69-4a0c-a6ea-783e9aa8bede.png)

I was hoping that in OpenBK this would relate to the Device Groups
![image](https://user-images.githubusercontent.com/70269175/210183328-25dbe4f4-cd24-4f2c-a17a-1dd7f30654dd.png)

But I can't get multiple devices to respond to commands I target there.

1) Is my assumption correct that device groups in OpenBK are not the same as Group Topics in Tasmota?
2) Can we have Group Topics in OpenBK?
3) Would the assumed syntax as "cmnd/[group topic]/power" and Payload 1 or 0 be correct?

Thanks
Niels

**Comment by openshwprojects** [comment]
Tasmota Device groups are this:
https://tasmota.github.io/docs/Device-Groups/
It has nothing to do with MQTT.

How group topics works? Are they... "listen only"?

So basically you want.... to set a group topic to "Bekens" on multiple devices, and then publish a "cmnd/Bekens/POWER" with "toggle" argument and they all listen and react?

What about replies - should the device publish something on group topic in a reply?

PS: "cmnd/bekendevice/power" with "0" or "1" or "toggle" already works

**Comment by NielsPiersma** [comment]
First, thanks for clarifying the difference between them. At least now it makes sense why I couldn’t get it to work.

well group topic 1 (how I use it) works the same as the device topic. But all the devices subscribe to this topic. If I send a command like cmnd/tasmotas/reset 3 they reboot and recalibrate WiFi. I like doing this for general housekeeping and tidying. But the same goes for mass changing the SSID and WiFi password on a regular basis.

if a device published something in the group topic all subscribers will execute the received command. So not something I would expect regular.

so it is just like the normal full topic where the device receives it command from, but has a name that is shared over all devices. One command there is a command for all (subscribers).

I would not post or publish any reply into the group topic.

I can conform the P S: "cmnd/bekendevice/power" with "0" or "1" or "toggle"  work fine. That what I was trying to expand.

Niels

**Comment by openshwprojects** [comment]
So basically:
1. add a field "GroupTopic" to gui
2. listen for commands on both cmnd/myBekenDevice1/POWER (etc etc) and /cmnd/myGroup/POWER
3. ... and execute those commands
And that's all?

**Comment by NielsPiersma** [comment]
Yes,

Thats it
Niels

**Comment by openshwprojects** [comment]
added:
![image](https://user-images.githubusercontent.com/85486843/210191712-e27b09e3-2fdd-49d3-a907-3ca7a2f02a81.png)

**Comment by NielsPiersma** [comment]
Super, I'll give it a try and let you know.
Niels

**Comment by NielsPiersma** [comment]
Well, I tried, but no response (yet). I configured "bekens" as the secondary group topic.

cmnd/obkBF512F1E/Power      Payload 1  == working
cmnd/bekens/Power      Payload 1 == not working.
![image](https://user-images.githubusercontent.com/70269175/210275895-86ed5ca0-f88a-455c-b7e4-41bc66e5df95.png)

Niels

**Comment by openshwprojects** [comment]
You must restart MQTT for changes to take place.

**Comment by NielsPiersma** [comment]
I can confirm this is working as expected. Excellent!!
Kudos!
Niels
