### ISSUE TITLE
Configuring flags via console / MQTT

### ISSUE THREAD

**Issue by NielsPiersma** [openshwprojects/OpenBK7231T_App#583]
Can the flags be configured via the console or MQTT cmnd?
The recent addition of the MQTT Group enables us to mass configure settings across many devices.
I would, for example, like to enable Flag 6,10 and 12 (Flags (Current value=4160)) for 25 Smart Plugs

Entering "Flags 4160" on the console results in;
Error:CMD:cmd flags NOT found (args 4160)

Having the possibility to update the flags via MQTT significantly improves the manageability of large groups of devices.

Essentially, I would request that all configuration commands be available via MQTT.

NIels

**Comment by openshwprojects** [comment]
Hello,
https://github.com/openshwprojects/OpenBK7231T_App/blob/main/docs/commands-extended.md
"SetFlag" command, but I can add a "Flags" command as well if you want, wait

**Comment by NielsPiersma** [comment]
Flags, with the corresponding number (enabling multiple options  in one go) would be helpful.
Niels

**Comment by openshwprojects** [comment]
Flags command added, altough I am not sure what when we reach 32+ flags, I tested 64 bit sscanf only on Beken and Windows, but it seems to work okay

**Comment by NielsPiersma** [comment]
working like a charm.
I can now distribute these setting by executing 

![image](https://user-images.githubusercontent.com/70269175/210726336-9e652f4b-a630-48d6-858d-02a3c4421054.png)

I am so happy that I can mass configure my OpenBeken devices now.!!!
NIels

**Comment by NielsPiersma** [comment]
Thanks for this new functionallity!
Niels

**Comment by iprak** [comment]
I think what we eventually need is a way to save/apply configuration. If a device had to be reset then the saved configuration could be reapplied. The same configuration could also be applied to other devices of same kind (minus the device id).
