### ISSUE TITLE
Config Data area corrupted

### ISSUE THREAD

**Issue by jkwim** [openshwprojects/OpenBK7231T_App#598]
**Describe the bug**
When config data is dumped using the WebApp tool some corrupted data is shown in the area where Startup Command is stored

In the example shown below, remnents of previous update of the start up command is also stored. That is I had a long string as the Startup Command and then I removed some commands so that the length of the string got shortened. However the earlier contant does not get wiped off before new content is stored.

**Firmware:**
- Version 1.15.276
- Device: Mini Smart Switch 
- Chip/model: BK7231N
- Device config: Not Applicable

**To Reproduce**
1. Store a long string of commands in the Startup Command option
2. Make another update of the Startup Command with a shorter string of commands
3. Go to 'WebApp'
4. Click on 'Flash' and then 'Read Config'
5. Scroll down to Area where Startup Command is saved
6. See error

**Screenshots**
```
05e0: 42 61 63 6b 6c 6f 67 20 50 6f 77 65 72 73 61 76 65 3b 20 53 74 61 72 74 44 72 69 76 65 72 20 4e  : Backlog Powersave; StartDriver N

0600: 54 50 3b 20 20 6e 74 70 5f 74 69 6d 65 5a 6f 6e 65 4f 66 73 20 2b 30 35 3a 33 30 3b 20 6e 74 70  : TP;  ntp_timeZoneOfs +05:30; ntp

0620: 5f 73 65 74 53 65 72 76 65 72 20 31 39 32 2e 31 36 38 2e 31 2e 32 33 35 00 53 74 61 74 73 20 31  : _setServer 192.168.1.235.Stats 1

0640: 2c 20 31 30 2c 20 36 30 2c 20 31 3b 20 6e 74 70 5f 74 69 6d 65 5a 6f 6e 65 4f 66 73 20 2b 30 35  : , 10, 60, 1; ntp_timeZoneOfs +05

0660: 3a 33 30 3b 20 6e 74 70 5f 73 65 74 53 65 72 76 65 72 20 31 39 32 2e 31 36 38 2e 31 2e 32 33 35  : :30; ntp_setServer 192.168.1.235

0680: 20 31 39 32 2e 31 36 38 2e 31 2e 32 33 35 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  :  192.168.1.235..................

```

**Comment by openshwprojects** [comment]
@jkwim  good spotting, but isn't it a normal behaviour of C strcpy function (or our strcpy_safe)?
The strcpy (or a safe version) does not clear the whole buffer, it just overwrites as much as is needed and then puts a NULL terminating character.
So this is not a bug, just a byproduct of how string copying work.
Of course, we could add a memset 0 to whole buffer on each change, but it woulnd't change anything except the fact that you wouldn't be able to peek into old part of previous string...
PS: Do you know that hard drives works in a similar way? Even if you delete a file, it still is there, as long as its not overwritten by new data.

**Comment by jkwim** [comment]
Ok. Agree with your explanation. I missed the NULL character :-)

I was doing this to see whether I did have any corruption in the Config when I tried to test the lfs_append command.

Thanks!
