### ISSUE TITLE
Random on/off swiches

### ISSUE THREAD

**Issue by DJVirus1980** [openshwprojects/OpenBK7231T_App#604]
- Version [e.g. 1.15.318]
- Device AUBESS FS-02HW
- Chip/model: BK7231N
Random swich on/off on 2 ch...........

**Comment by openshwprojects** [comment]
Are you using power save? This device tends to have a very low quality power supply.

**Comment by DJVirus1980** [comment]
No. I did not use power save.

**Comment by openshwprojects** [comment]
Are you using ToggleChannelOnToggle?
There is not much information....
Which version breaks things for you?

**Comment by DJVirus1980** [comment]
I am using dinput. Breaks from 1.15.309. Using P10&P11 for dinput.

**Comment by openshwprojects** [comment]
@DJVirus1980  I've pushed the older version (but still fixed to respect variable delta time and also respects instant touch reaction - if set, debounce time is lowerE), can you check?

**Comment by openshwprojects** [comment]
@DJVirus1980 any news?

**Comment by DJVirus1980** [comment]
Hi. On 1.15.324 work fine.

**Comment by openshwprojects** [comment]
Thank you. Hmm.... so dinput was really getting much noise it seems. Good to know. Thank you for testing.
