### ISSUE TITLE
Rocker switch sync

### ISSUE THREAD

**Issue by DiegoJp** [openshwprojects/OpenBK7231T_App#611]
Hello, I have installed OpenBeken in a Aubess MINI Wifi switch like this:
![imagen](https://user-images.githubusercontent.com/41808318/212550003-2eeb88cf-d4b2-426a-b121-37e5858f2409.png)

I loaded the config from the webapp like this: 
![imagen](https://user-images.githubusercontent.com/41808318/212550069-c4127424-7bfd-4f9a-be71-801e80fab488.png)

However is missing a functionality from the Smartlife/Tuya app in which the button status (S1 and S2 connection) is synced to the channel status. It's called like 'switch type setting' and the options as follows:

![imagen](https://user-images.githubusercontent.com/41808318/212549983-147cab84-8db0-45aa-8184-468b14caccbf.png)

- rocker switch - flip to change state (this is the default behaviour in Tuya fw and OpenBeken fw)
      - On physical button flip to **on**, it will toggle channel (if it's on will turn to off and viceversa)
      - On physical button flip to **off**, it will toggle channel (if it's on will turn to off and viceversa)
- rocker switch - state synchronous (this functionality is missing)
      - On physical button flip to **on** will turn on channel, if channel it's already on **it will remain on.** 
      - On physical button flip to **off** will turn off channel, if channel it's already off **it will remain off.**

This funcionality is useful for physical switches that are labelled as "On / Off" and it's more intuitive than the default behaviour.
I hope this is understandable. I have not tried to make any changes in Config module as it seems that are not well documented in the github wiki.

Keep the good work, many thanks in advance!

**Comment by openshwprojects** [comment]
Hello, I think you are looking for "ToggleChannelOnToggle" pin role?

**Comment by DiegoJp** [comment]
> Hello, I think you are looking for "ToggleChannelOnToggle" pin role?
> 
> Or just for dInput?
> 
> state synchronous is dInput, digital input, copies values to channel. Albo exists in dInput_n form, an inversed one

Yeah, that wast it! Set the corresponding pin to Dinput_n and now works as intended!
![imagen](https://user-images.githubusercontent.com/41808318/212554576-c9629a2a-d931-468a-99af-7d5065d08f02.png)

Many thanks
