### ISSUE TITLE
BK7231T Bug  button switching

### ISSUE THREAD

**Issue by az-src** [openshwprojects/OpenBK7231T_App#615]
Hello. The error of the buttons operation migrated from the original SDK. Or rather, it doesn't work correctly. The relay switches on a falling edge (finger release). Very uncomfortable and uncomfortable. Help make buttons work on rising edge(finger touch)

**Comment by openshwprojects** [comment]
Hello, you are most likely looking for a "Instant Touch Reaction" flag which is available in flags menu.

**Comment by az-src** [comment]
I'm not sure, but I'll check now, thanks

**Comment by az-src** [comment]
Thanks a lot !!! I didn't know where to look. Everything works great!!!

**Comment by openshwprojects** [comment]
By the way, it's not a bug, it's a feature.

Without delayed click event, the "double click" would fire both a click and dbl click.
