### ISSUE TITLE
Ability to rename toggle buttons

### ISSUE THREAD

**Issue by Wolfieeewolf** [openshwprojects/OpenBK7231T_App#618]
Would like to be able to rename the toggle buttons to what they control. I have a few double/quad switches and it gets a little confusing after a while on what is doing what. would be good to be able to label the toggles to help with troubleshooting.

If f this info could be dragged over to home assistant as well that would be great. Most of the time I just get 1 or 2 as the switch name. I have to turn it on and off to work out what it is controlling. I know it's not a huge issue but its just an extra step I have to take. Also means I don't have to relabel them over and over again in home assistant, google and alexa.

**Comment by Wolfieeewolf** [comment]
Thanks for adding. sorry for the delayed reply. 

I'm not overly familiar with the autoexec.bat. I know how to create a file but other than that not sure what to do from there. I'm sure I can work out.

**Comment by openshwprojects** [comment]
Launch Web Appliation -> LittleFS -> create  file, save, reboot

**Comment by kapplejacks** [comment]
I got it working thanks to your help @openshwprojects . 

Yes you must connect the device to your wifi, then you can connect to the devices local GUI, select the launch web application. Once there, filesystem, scan files (nothing will be found) and then create file. This will auto make your autoexc.bat file. 

From there simply paste in your commands one line at time, id reference the command list here ([Command Doc ](https://github.com/openshwprojects/OpenBK7231T_App/blob/main/docs/commands.md)) SetChannelLabel 1 Outlet1 ; save that and reboot, now your outlets names are loaded on reboot. 

Personally, id like to either have it remove the word Toggle, or swap the lettering around, so ON / OFF is in the green red button box and the outlet name is where the ON / OFF currently is above the toggle box. 
<img width="197" alt="Screen Shot 2023-02-16 at 8 44 04 PM" src="https://user-images.githubusercontent.com/44504711/219536434-34a643de-a7dc-4a74-8ad2-ab8a52401731.png">
Then you can remove the word toggle all together.

**Comment by Wolfieeewolf** [comment]
you can also use 

`setButtonLabel 1 "Light ON/OFF"`

Might need to also use it with 

`startDriver httpButtons`

Closing as issues resolved
