### ISSUE TITLE
Cloudcutter dead after firmware install - moes WIFI Smart Dimmer Module 105 (TuyaMCU dimmer, WB2S based)

### ISSUE THREAD

**Issue by ElGranPepo** [openshwprojects/OpenBK7231T_App#633]
**Describe the bug**
Device not responding after firmware has been installed

**Firmware:**
- Version OpenBK7231N_UG_1.15.347
- Device? 
- Chip/model: WB2S
- Device config?

**To Reproduce**
1. Run Tuya cloudcutter and choose device as moes moes WIFI Smart Dimmer Module 105
2. Choose firmware as OpenBK7231N_UG_1.15.347
3. reset device 2 times as per instructions
4. device will be removed from Tuya and firmware is uploaded
5. device becomes unresponsive

**Comment by openshwprojects** [comment]
You are using incorrect firmware version. WB2S, according to docs, is BK7231T based, so you should OpenBK7231T_UG.
