### ISSUE TITLE
Rename project, as it has grown out of Beken and now a fully fledged multiplatform app, supporting many IoT platforms?

### ISSUE THREAD

**Issue by openshwprojects** [openshwprojects/OpenBK7231T_App#638]
It was brought to my attention that our project name is obsolete and may make some people confused or unhappy, as Beken is just a BK7231T and BK7231N manufacturer.

We are now currently supporting BK7231T and N, but also W600/W601, W800/W801, BL602 (possible 604 and 700-s as well), and XR809, and of course also Windows (with simulator), with more platforms work in progress.

I think we should consider getting a more "multiplatform" name, that does not contain the manufacturer name of a certain platform, to make everything clear and keep certain people happy.

So my question is - do you have any ideas for a possible future name for our multiplatform IoT firmware?

**Comment by DiegoJp** [comment]
Since they are all based on Tuya, how about OpenTuyaBreak? (added break as a wow factor lol)

**Comment by Wolfieeewolf** [comment]
I ran you question through ChatGPT a few times and it spat out these 

Sure, here are a few suggestions for a new name for your multi-platform IoT firmware:

    IoT Hub
    CrossConnect
    OmniCore
    OneOS
    SmartBridge
    UniFirm
    NexusNet
    FusionCore
    FlexiIoT
    GlobalNet

    IoT Fusion
    PlatformHub
    Universal IoT
    InterConnect
    IoT Nexus
    The Connector
    IoT Synergy
    MultiIoT
    All-in-One IoT

    ConnectCore
    OneIoT
    AllNodes
    IoT Hub
    SmartNet
    MultiMesh
    EdgeFuse
    PlatformPlus

These names aim to convey the idea of a unified, all-encompassing, and flexible platform that can connect and support multiple IoT devices

I like Crossconnect or maybe some kind of mashup of something else on the list.

**Comment by openshwprojects** [comment]
We can't obviously use Tuya trademark, that would be a change for worse. Futhermore, W600, W800, etc are non-Tuya.
BL602 as well. 
I will consult that our internal Discord as well.

**Comment by kuba2k2** [comment]
Internal Discord? What a shame it's not public. I remember you saying you wanted to keep everything public, and indexable by search engines, for example on the Elektroda forum. I wonder why did you change your mind.
