### ISSUE TITLE
Wrong day of week on S09 / tuyaMCU

### ISSUE THREAD

**Issue by gromdar** [openshwprojects/OpenBK7231T_App#649]
Build on Jan 10 2023 01:17:50 version 1.15.305 Chipset BK7231T
Hi all, 
I installed OpenBK on my new toy S09 desktop therm+higro+display+ir device. It is equipped with MCU that is responsible for sensors and LCD. I managed to configure everything somehow to set time, anyway it displays incorrect day of week - just previous day.
It displays for ex : Thursday  03/02/2022. 

I driver I see that day is intentionally changed but in my case it seems to be wrong . 
drv_tuyaMCU.c  478  TuyaMCU_Send_SetTime,  

 		if (pTime->tm_wday == 1) {
			tuya_day_of_week = 7;
		}
		else {
			tuya_day_of_week = pTime->tm_wday - 1;
		}

Could it be somehow configurable ?  

cheers 
Artur

**Comment by openshwprojects** [comment]
Huh... okay, give me 30 minutes and I will add a flag for that.
Thanks!
But it's very strange, I remember doing this change for my S06.
So... you need tm_wday + 1?

**Comment by gromdar** [comment]
I would say S09 needs exact tm_wday without change. The other thing is what this mcu really expects . I hope it is not 0 based value...

**Comment by openshwprojects** [comment]
@gromdar  I was about to push a fix but It's against what you are saying.
![image](https://user-images.githubusercontent.com/85486843/216663897-9d88f37c-c953-484b-993c-7310b3cd91f2.png)
![image](https://user-images.githubusercontent.com/85486843/216663925-e2b8f276-24bd-46ef-9e34-feca56cc7be8.png)
Input is [0,6] range and Tuya wants [1,7] range...

**Comment by gromdar** [comment]
Your code is fine and should correct my issue. I was not aware of tm_wday format. According to your explanation that should be a correct fix.

**Comment by openshwprojects** [comment]
No problem, I am genuinely surprised that this wrong day have slipped my attention earlier. I just hope I didn't break anything in the process, but it doesn't seem like it.

Thanks for spotting that issue!

By the way, we don't have S09 full review on our list (just a mention):
https://openbekeniot.github.io/webapp/devicesList.html
if you want, consider posting a short review/template/config:
https://www.elektroda.com/rtvforum/topic3950844.html

**Comment by gromdar** [comment]
I loaded snapshot build OpenBK7231T_1.15.408.rbl and now day of week is correct before midnight Friday, after midnight Saturday. 
Well done, thanks
