### ISSUE TITLE
urldecode2_safe not so safe

### ISSUE THREAD

**Issue by jbanaszczyk** [openshwprojects/OpenBK7231T_App#65]
https://github.com/openshwprojects/OpenBK7231T_App/blob/e109dce22f497413f28c199064a7d22b46fe749b/src/new_common.c#L60

In this case `dst` will not be terminated by `null`

**Comment by btsimonh** [comment]
good spot, thankyou.

we should 
				if(curLen >= maxDstLen-1){
					*dst = 0;
					break;
				}
