### ISSUE TITLE
SwitchMode corresponding

### ISSUE THREAD

**Issue by gfucka** [openshwprojects/OpenBK7231T_App#679]
Hi,
I flashed firmware on a tuya mini switch.
I want everytime external switch S1-S2 is toggled the relay change state.
How can I do?
In tasmota I use SwitchMode.
Thanks

**Comment by openshwprojects** [comment]
Hello,
ToggleChOnToggle?

**Comment by gfucka** [comment]
Thank you for answer me. I must write it on web application?

**Comment by gfucka** [comment]
Ok I get it, in the config.
Thankyou so much
