### ISSUE TITLE
Any plans for supporting TYLC5?

### ISSUE THREAD

**Issue by ok11** [openshwprojects/OpenBK7231T_App#702]
Not a bug, rather a question/suggestion. Light sources at Tuya use among others [TYLC5](https://developer.tuya.com/en/docs/iot/wifilc5module?id=K9605t3bpxf75) module. I have dismantled a couple of my bulbs to figure out that they are based on that chip. Would it be possible to include it to the list of supported ones?

Thanks!

**Comment by openshwprojects** [comment]
Hello, TYLC5 is ESP8285, so why would anyone need to support it? Tasmota already got it...   we could support ESP platform, but it;s a low priority, I think.

**Comment by ok11** [comment]
Hey, thanks for the hint, it was not clear to me that TYLC5 is an ESP family. They I will look towards Tasmota/Tuya-convert. Thanks again!
