### ISSUE TITLE
Melink bulb has switched colors

### ISSUE THREAD

**Issue by mikimause9** [openshwprojects/OpenBK7231T_App#707]
Hi,
I’ve recently found melink light bulbs. They were very cheap and were said to work with eWeLink. I was hoping that they had chip supported by this project, and they had!(bk7231n) I reprogrammed one of them and after reassembling the bulb I noticed that the red and blue colors are switched(when I set the blue color bulb lights red and vice versa) The bulb has a BP5758D chip. I've tried to find some options in the software, but I failed. Is there any possibility to change that?

**Comment by openshwprojects** [comment]
Hello, you should use BP5758D_Map command.
BP5758D 0 1 2 3 4 etc etc try to swap indexes.

**Comment by mikimause9** [comment]
Thanks, it worked!
