### ISSUE TITLE
drv_main.c

### ISSUE THREAD

**Issue by Meridian85** [openshwprojects/OpenBK7231T_App#731]
In the project from version "OpenBK7231T_App-1.15.585" driver for BL0942 SPI was added
In the "drv_main.c" file, the definition of "ENABLE_DRIVER_BL0942" is the same for SPI, should there be "ENABLE_DRIVER_BL0942SPI"?

Thank you.

**Comment by openshwprojects** [comment]
You are correct, it seems that our contributor forgot to change the define. I will fix it right now.
