### ISSUE TITLE
Pin Settings for Tuya 5in1 RGBCCT LED Strip Controller

### ISSUE THREAD

**Issue by Matsched** [openshwprojects/OpenBK7231T_App#749]
Hello guys!
ive just bought [this RGBCCT 5in1 LED Strip Controller Tuya](https://de.aliexpress.com/item/725319185.html) from Ali with a BK7231T and flashed openBeken on it. Im missing the controller in the Device Lust under /app? and have no clue which Pin is R,G,B,CW,WW,V etc.
Can i broke the device by try and error? Where can i get the information about my device?

Edit: I found on dev site from tuya this Pinout: https://developer.tuya.com/en/docs/iot/wb3s-module-datasheet?id=K9dx20n6hz5n4#title-5-Interface%20pin%20definition
Maybe i can use this for my configuration in openbk?

thanks!

**Comment by openshwprojects** [comment]
Hello, we are usually using forum for devices discussion:
https://www.elektroda.com/
but yes, you must open device (or read flash for analysis, before flashing obk) and see which GPIOs are used for PWMs. There is 6 possible PWMs in BK, so you can also resort to guessing.

**Comment by Matsched** [comment]
thank you very much!
