### ISSUE TITLE
Miboxer FUT036w with CB3s Problems

### ISSUE THREAD

**Issue by MarcoL-81** [openshwprojects/OpenBK7231T_App#758]
Hello, i have the led controller miboxer Fut036w with Wifi and 2,4gHZ.
i have flash with the ObenBK Firmware. 
The Flashing and the CRC is OK.
CRC matches 0x4ACF98A4!
Writing file data to chip successs.
When i connect the power i can see the Wifi. 
Then i can connect to my home Wifi
i can connect to mqtt.
But i cant control it the web.
i only can switch and dimm with the local switch, like before. 
and the flashing led on the pcb is also like before. it seems that the old firmware is active. but the  openbk is running with mqtt and so on.
what is my error?
![D9F31999-98F0-4F5D-AD7C-E94108822880](https://user-images.githubusercontent.com/129629083/229317531-751d58f8-9bd2-4616-bbb7-c8b2a3a55c70.jpeg)
![AFBFE30D-8006-4D46-804B-9024CCE201FA](https://user-images.githubusercontent.com/129629083/229317543-864dfe8b-68aa-444d-a84f-ca87361caeb8.jpeg)
![14893FB1-4705-4BB1-98A3-838E97115FAF](https://user-images.githubusercontent.com/129629083/229317580-12e42f6b-e39f-476d-b2cd-35c8b55398ff.jpeg)
![A95EEE00-1C58-4478-AD73-052BF98574FB](https://user-images.githubusercontent.com/129629083/229317614-9154cc95-3f9f-4aed-8712-6ef0e79a6b64.jpeg)

**Comment by openshwprojects** [comment]
Please post in our devices forum:
https://www.elektroda.com/rtvforum/forum390.html
but in general, this is a TuyaMCU device and may require further setup/research.

**Comment by MarcoL-81** [comment]
ok, i make a post in the forum.
Zhe problem is that there is a second µC. I have dismount it and then its working.
But i will make some adjustments about the BTN_SmartLED 
https://www.elektroda.com/rtvforum/topic3969126.html
