### ISSUE TITLE
TasmoAdmin runtime stats are way off

### ISSUE THREAD

**Issue by Wolfieeewolf** [openshwprojects/OpenBK7231T_App#768]
**Describe the bug**
When using TasmoAdmin runtime stats they are way off. See attached image

**Firmware:**
- Version 1.15.656
- Device? All devices
- Chip/model: BK7231T/BK7231N
- Device config? Yes

![Screenshot 2023-04-06 122023](https://user-images.githubusercontent.com/24477216/230256491-1c0feac4-c1f8-4de2-a9c9-51d4fb13c3fd.jpg)

**Comment by openshwprojects** [comment]
Maybe it needs NTP running? Or is it uptime in seconds?

What do you get if you use http://192.168.0.202/cm?cmnd=status (enter your IP inside of mine)?

I get: "Uptime":"0T12:44:04","UptimeSec":45844 in that JSON, which seems ok ?

**Comment by Wolfieeewolf** [comment]
I get this with the /cm?cmnd=status 

![Screenshot 2023-04-07 083020](https://user-images.githubusercontent.com/24477216/230506459-66ee9425-aab8-4245-9ccb-421443463814.jpg)

When I run the NTP driver it seems to have fixed the problem.

**Comment by openshwprojects** [comment]
Sorry but are those valid values? Are they invalid without NTP? NTP should not be required for uptime counting..

**Comment by Wolfieeewolf** [comment]
Just did some testing with the uptimes with and without NTP.

With - Uptime : "0T00:00:55" - UpTimeSec : 55 - Matches uptime in TasmoAdmin


![Screenshot 2023-04-10 143642](https://user-images.githubusercontent.com/24477216/230826964-6d63b3cb-1c0e-4c2f-83a7-67e18b722015.jpg)


Without - Uptime : "0T00:01:14" - UpTimeSec : 74 - Doesn't match uptime in TasmoAdmin

An interesting note is that the StatusTIM times are all wrong 

![Screenshot 2023-04-10 143344](https://user-images.githubusercontent.com/24477216/230826763-3b5c20c5-1b83-4613-9599-74c5a96ecf8b.jpg)

This would explain the huge Uptime number in TasmoAdmin if it is calculating the uptime from 1970.

**Comment by openshwprojects** [comment]
They are 1970 while you don't have NTP running.

**Comment by Wolfieeewolf** [comment]
Correct. Seems to work fine when the NTP is running

**Comment by Dheenhasty** [comment]
Yes the Tasmota schema use the start time to do his calculation ..... so NTP is needed. i saw that in tasmoadmin too

**Comment by Wolfieeewolf** [comment]
Closing this as the NTP driver has fixed the issue
