### ISSUE TITLE
Getting back wrong MQTT state of led_enableAll/get

### ISSUE THREAD

**Issue by nospam2k** [openshwprojects/OpenBK7231T_App#814]
I'm unable to figure out how to request (MQTT) led_enableAll/get in order to get the correct response from the device.
Ex. The light is OFF and I send from mosquitto_pub:
```
openbk/lights/desk-light1/led_enableAll/get (null)
```
I get back:
```
openbk/lights/desk-light1/0/get 1
```

**Firmware:**
- Version 1.17.54
- Device?  Daybetter w/BP5758D_DAT/BP5758D_CLK
- Chip/model: BK7231T

NOTE: If I send cmnd/openbk/lights/desk-light1/publishAll led_enableAll comes back correctly.

**Comment by openshwprojects** [comment]
Thank you for reporting issuei. It should be fixed now,c heck latest build. An appropriate self test has been also added to make sure that problem does not appear again in the future.

**Comment by openshwprojects** [comment]
Hello, is it working for you now?

**Comment by nospam2k** [comment]
Sorry for not getting back. I did test it and it's working. I switched over to using tele, but yes led_enableAll is working.
