### ISSUE TITLE
Bl602 Not saving config params

### ISSUE THREAD

**Issue by nospam2k** [openshwprojects/OpenBK7231T_App#818]
I flashed a BL602L20 chip from a daybetter bulb following the tutorial using the lates Boufallo Dev Cube software. It comes up as an AP and I can connect, but it won't save any config parameters.

![Screen Shot 2023-04-29 at 12 46 56 PM](https://user-images.githubusercontent.com/1284287/235321488-a4746eb6-0f8a-4536-a303-6e7da31b9ee7.png)

**Comment by openshwprojects** [comment]
Hello, does it also happen with older builds? Something from about a week ago?

**Comment by nospam2k** [comment]
Can I downgrade OTA or do I need to reflash. I've removed all the Uart flash wires.

**Comment by nospam2k** [comment]
Ok, I think it was just a corrupt flash. I installed a previous version, but I got better and shorter wires and that flashed ok. I then reflashed the latest version and it was ok. I'm going to close this.
