### ISSUE TITLE
[Contact sensor] Deep sleep during initial configuration, after flashing the firmware

### ISSUE THREAD

**Issue by jacyker** [openshwprojects/OpenBK7231T_App#828]
**Describe the bug**

The soldering and flashing of alternative firmware (Openbk7231n) were supposed to be the harder part. However, the problem is with the configuration because the device goes into what seems to be deep sleep mode after a few seconds, thus turning off the WiFi. I don't know who came up with this, but it's pure sadism because to configure the device, you have to keep "opening and closing doors" all the time. Is there anything that can be done about it? PowerSave 0 and DeepSleep 0 commands don't help.

**Firmware:**
- OpenBK7231N_QIO_1.17.113
- Tuya Contact Sensor
- Chip/model: CB3S/BK7231N

**Comment by openshwprojects** [comment]
Hello, well, first of all, are you really sure it's OBK sleeping? Maybe it's TuyaMCu device and TuyaMCU is turning off the BK chip. Please post some photos.

**Comment by jacyker** [comment]
You're right. It is most likely the case that CB3S is active only for a while (TuyaMCU protocol). Is it possible to get around this somehow programmatically, or by plugging the power supply directly into CB3S to set OpenBK7231T?
