### ISSUE TITLE
[Feature Request] Option to disable MQTT

### ISSUE THREAD

**Issue by TomTheGeek** [openshwprojects/OpenBK7231T_App#833]
Some way to disable it completely would be nice. I don't need MQTT it's just a complication most of the time and unnecessary. 

I guess you could make MQTT a separate Driver that has to be specifically loaded. 

Thanks!

**Comment by openshwprojects** [comment]
Hello, MQTT is disabled when you leave host field blank. It does not take much CPU time.

**Comment by Jonsonmon** [comment]
After one time you fill the mqtt ip field, You cannot remove it. You should make a command to clear mqtt settings (mqtt factory reset) .

**Comment by openshwprojects** [comment]
I think it's safe to be closed. You just need to clear MQTT fields (ip, etc)
