### ISSUE TITLE
W600 cannot save settings

### ISSUE THREAD

**Issue by henkiejan1** [openshwprojects/OpenBK7231T_App#835]
**Describe the bug**
I flashed before my W600 module and works fine. But with the new release i can put in wifi settings for x times but it looks like it saves nothing and booted just as AP... If i press on the scan wifi network button i got: W800 TODO. The downloaded latest version i got did not have the alpha extension...

**Firmware:**
- Version [OpenW600_1.17.127.fls]
- Device: Wavgat WIS600-01s
- Chip/model: WinnerMicro W600
- Device config?

**To Reproduce**
Flash a W600 device and try to connect to wifi

**Comment by openshwprojects** [comment]
Hello, the WiFi network scan is TODO, as described, but still, device should save settings.
I can try to find my W600 board and check.
In a meantime, can you flash by UART?
Can you try version from before April 20, 2023 and check if there also config save is broken?

**Comment by henkiejan1** [comment]
Update: flashed the version op 19 april and that works! But needed to set static ip settings but ok. :)

**Comment by openshwprojects** [comment]
So you're saying that newer version is broken? Are you able to tell when exactly it broke?

**Comment by dy008** [comment]
I also have the same problem. After flashing into the 1.17.129 version, the wifi settings cannot be saved, only the AP function is enabled, and no configuration can be done. Flashing into 1.17.06 is normal

**Comment by openshwprojects** [comment]
Fixed in:
https://www.elektroda.com/rtvforum/viewtopic.php?p=20616695#20616695
