### ISSUE TITLE
Openbk7231T - cannot connect to wifi

### ISSUE THREAD

**Issue by ladykira2022** [openshwprojects/OpenBK7231T_App#846]
I was able to flash using cloudcutter but it seems it does not connect to the wifi.
When i press the scan wifi - i get a lot of SSID (there are only 3 in the area) with strange character into the names.
Any idea what to do next?

I flashed a second une using ESP Kickstart-bk7231t - same issue.
The device is a RGB Led that was having main module on 2.9.16

WIFI is  based on Unifi infrastructure , 2.4, no strange characthers in SSID or password.
LE Edit: I opened one up: the chipset is wb2s - should be supported 

<img width="897" alt="Screenshot 2023-06-07 at 12 06 56" src="https://github.com/openshwprojects/OpenBK7231T_App/assets/119303364/a00df808-6f5a-418e-a53a-6d4edaa05a69">

<img width="824" alt="Screenshot 2023-06-07 at 12 15 10" src="https://github.com/openshwprojects/OpenBK7231T_App/assets/119303364/4cec1da4-083f-4434-9f08-9db599489664">

**Comment by openshwprojects** [comment]
Have you tried resetting RF partition? Is your router a mesh network?

**Comment by ladykira2022** [comment]
There are 4 Unifi AP with roaming. I changed closer to another AP and was able to connect, finally.
Seems the WB2s chipset is quote sensitive to signal. On top it is an outdoor metal lamp - so that might also not help
//
P.S. Is there a way to flash from OpenBK to ESPHome (or the other way around)? Now I have one lamp on OpenBK and the other on LibreTiny esphome.
