### ISSUE TITLE
"ErrorMsg":"BFLB READ FLASH JEDEC ID FAIL"

### ISSUE THREAD

**Issue by pdrobek** [openshwprojects/OpenBK7231T_App#848]
**Describe the bug**
Unable to flash chip BL602

**Firmware:**
Tried OpenBL602_1.17.124.bin and OpenBL602_1.17.133.bin

**To Reproduce**
Always occurs with 2 different  led controllers

**Screenshots**
![obraz](https://github.com/openshwprojects/OpenBK7231T_App/assets/4559534/8664ad6d-f820-4873-a7c7-a286bbdbd6e7)

**Comment by openshwprojects** [comment]
I think it may have been discussed on Elektroda some time ago. You may need to try the newest flasher and maybe modify the partition settings.

**Comment by pdrobek** [comment]
My bad. Closed
