### ISSUE TITLE
[Question] How do I change the NTP Server?

### ISSUE THREAD

**Issue by viny182** [openshwprojects/OpenBK7231T_App#851]
Hello Guys,

In a BK7231N chip flashed with version 1.17.54, how do I setup a manual NTP Server?

I try to run the command NtpServer on the console, but I'm getting the command unknown error, as below...
![image](https://github.com/openshwprojects/OpenBK7231T_App/assets/65199912/fca6059e-4d6c-4ceb-af84-1118dfab95d5)

Also, on the homepage, I See the NTP server enabled is the 217.147.223.78 from pool.ntp.org. This what I need to change.

![image](https://github.com/openshwprojects/OpenBK7231T_App/assets/65199912/6c1ba0a2-cc89-48d4-8daf-820cbef36749)

**Comment by ataa** [comment]
Try:
`ntp_setServer` command.

**Comment by viny182** [comment]
> Try:
> 
> `ntp_setServer` command.

Unfortunately I've got the same output: 'Unknow command'

**Comment by ataa** [comment]
I am on version 1.17.104 (BL602) and it works on mine, make sure ntp driver is loaded.

`ntp_setServer 192.168.20.1`
```
Info:NTP:NTP server set to 192.168.20.1
Info:CMD:[WebApp Cmd 'ntp_setServer 192.168.20.1' Result] OK
```

**Comment by viny182** [comment]
> I am on version 1.17.104 (BL602) and it works on mine, make sure ntp driver is loaded.
> 
> 
> 
> `ntp_setServer 192.168.20.1`
> 
> ```
> 
> Info:NTP:NTP server set to 192.168.20.1
> 
> Info:CMD:[WebApp Cmd 'ntp_setServer 192.168.20.1' Result] OK
> 
> ```
> 
> `ntp_info`
> 
> 
> 
> ```
> 
> Info:NTP:Server=192.168.20.1, Time offset=0
> 
> Info:CMD:[WebApp Cmd 'ntp_info' Result] OK
> 
> Info:NTP:Seconds since Jan 1 1900 = 3895663524
> 
> Info:NTP:Unix time  : 1686674724
> 
> Info:NTP:Local Time : 2023/06/13 16:45:24
> 
> ```

Errmmm, my bad.

I tried in other device where NTP driver was stopped.

I confirm Starting NTP and runing ntp_setServer x.x.x.x works.

Thank you @ataa !
