### ISSUE TITLE
Garage door opener - cannot find configuration

### ISSUE THREAD

**Issue by AliMickey** [openshwprojects/OpenBK7231T_App#858]
Hi there, i have successfully flashed this simple garage door opener relay with openbk and have connected to wifi and mqtt.

I am having trouble setting the configuration correctly, I have tried the automatic Tuya partition config downloader, but it finds no meaningful data on it.

https://www.amazon.com.au/dp/B07QG7RGFW

It's using a WB2S: https://developer.tuya.com/en/docs/iot/wb2s-module-datasheet?id=K9ghecl7kc479

**Comment by openshwprojects** [comment]
Hello, please open a topic on our forum (so we can add it to teardowns list), provide as much information as you can and we  can guide you step by step with the setup:
https://www.elektroda.com/rtvforum/forum51.html
You can use GPIODoctor to figure out GPIO roles.

Github issues are used by us mostly to discuss implementation issues, bug reports, etc, forum is mostly for end user help and guidance.

You can also maybe see this topic:
https://www.elektroda.pl/rtvforum/viewtopic.php?t=3936372&highlight=
