### ISSUE TITLE
CBU-NL Flashing Help Required

### ISSUE THREAD

**Issue by Nailik** [openshwprojects/OpenBK7231T_App#861]
I have troubles backing up the firmware of the CBU-NL with the GUI tool.

According to https://developer.tuya.com/en/docs/iot/CBU-NL-module-datasheet?id=Kbaeq6j53y0yg 
it uses the BK7231N chip.

I traced the following pins (also according to data sheet).

I tried using reset via the CEN pin and also power on/off and also different Baud Rates but i always get the error:

getting bus failed

![PXL_20230620_124212983 MP](https://github.com/openshwprojects/OpenBK7231T_App/assets/13292441/280d9d16-ac82-4e22-a8aa-3527457381c6)

**Comment by openshwprojects** [comment]
Hello, this looks like not a bug report, but like an end-user per-device help request, so it belongs to our forum:
https://www.elektroda.com/rtvforum/topic3984948.html
Let's continue discussion there.

**Comment by Nailik** [comment]
fixed anyway, i used rx01 and tx01 the rx tx to programm are on the other side.
