### ISSUE TITLE
Autostart doesn't work

### ISSUE THREAD

**Issue by alex3594** [openshwprojects/OpenBK7231T_App#87]
Hello!
Is there any way to switch on the light for the Tuya E27 LED bulb when it powers up?
I tried to add "color #000000FF" to the "startup command line", but it didn't help. 
Thanks!

**Comment by openshwprojects** [comment]
Really? Let me check... RGBCW Tuya bulb here. E27.

![image](https://user-images.githubusercontent.com/85486843/170337557-561c8f7f-7432-4fab-9184-a8687c2e9f05.png)

after reboot:
![image](https://user-images.githubusercontent.com/85486843/170337617-356624c8-8fe3-4b1b-b738-f0d537c03dc7.png)

well, it works for me. Remember thatyou can also use new led driver commands as well.

**Comment by alex3594** [comment]
Sorry, I meant I need to make it light right after the startup (when you powered the device up). 
All controls work fine except autostart the light.

**Comment by openshwprojects** [comment]
Really? That's interesting, let me check....

ah, now I see what you mean! It's not a bug, it's a feature.
If you do more than 2 reboots without waiting for 30 seconds, then device assumes that it has a technical problem and enters "safe mode" so youi can recover it from bad config.

So it works even if you unplug, but only if you wait 30 seconds after reach reboot.

**Comment by alex3594** [comment]
Thanks for the clarification! It works fine after I wait for 30 seconds!

**Comment by alex3594** [comment]
It will be great if you add something like "5 restarts in 10 seconds" for the recovery mode if possible.
Thanks!

**Comment by openshwprojects** [comment]
@alex3594 
i have changed it and now you need at least 5 boot failures to run safe mode (but still full boot counts as 30 sec)
https://github.com/openshwprojects/OpenBK7231T_App/commit/65210cd44b44e8a7ffa112f5cd3990e7e9f848de
will it be enough?

**Comment by alex3594** [comment]
@openshwprojects 
Thanks for the update, but I think I need this timeout to be removed (or make it 1 second) if possible. 
Because in my scenario I may need to power off the light, then power it on again in a few seconds. 
But I'm pretty sure it will not be powered off on on 5 times.

**Comment by openshwprojects** [comment]
@alex3594 
What about this?
https://github.com/openshwprojects/OpenBK7231T_App/commit/35470c431c71e7e8babbcdbe51517907b02bdbff
This will let you to set time required for full boot (at least 1 second)

but use wisely, it will be very easy to lock yourself out with such a short boot ok delay

not fully tested

Time is changed in Config->General

**Comment by openshwprojects** [comment]
Well, you haven't responded in a long time, and requested feature is implemented, so I will assume that's it resolved.
