### ISSUE TITLE
[QUESTION] How to update and manage multiple devices OTA?

### ISSUE THREAD

**Issue by viny182** [openshwprojects/OpenBK7231T_App#875]
Hello all,

I currently have 15+ devices running OBK, and I was wondering if there is an easy way to update them all at once, instead of going to each device and updating them manually...

I see we have available the command "ota_http", which requires a local http server.

Is there a way to send this command trough MQTT to all devices at once to make them update at bulk? Of course I would do it only after testing with at least one device....

**Comment by viny182** [comment]
I think I figured this out... 

If I send the command to the Group Topic, all devices will reply.. here is how I've done with home assistant Mosquitto integration and local http server:

![image](https://github.com/openshwprojects/OpenBK7231T_App/assets/65199912/c93e6c43-6865-4427-9b3d-5ed9aad6ad96)


![image](https://github.com/openshwprojects/OpenBK7231T_App/assets/65199912/c938d287-f161-45ba-8665-a5520847b243)

**Comment by ataa** [comment]
# pyOpenBeken
An easier way to manage your [OpenBeken](https://github.com/openshwprojects/OpenBK7231T_App) devices.

The purpose of this project is to ease the control of multiple devices avoiding all manual tasks.

### Features
* Send commands
* Setup mqtt & HA autodiscovery
* Read file system
* Push OTAs and restore FS

### Planned features
* Scan for devices
* Set pins (Roles, Channels)
* Control device
* Set other options

https://github.com/gargomoma/pyOpenBeken

**Comment by openshwprojects** [comment]
Please remember to separate T and N!
