### ISSUE TITLE
Fan has four speeds off/low/med/high

### ISSUE THREAD

**Issue by jenniferlee1818** [openshwprojects/OpenBK7231T_App#88]
Most fans have these same 4 speeds.  I have already updated my personal firmware, but I don't know how to do a pull request.  Sorry about that.  I'll learn I'm sure.  this is echojjj

**Comment by openshwprojects** [comment]
Here it is: https://github.com/openshwprojects/OpenBK7231T_App/commit/c02db06cb3440ce9ac95ce74cf3177813d2fae34
so we support both "OffLowMidHigh" and "LowMidHigh"
