### ISSUE TITLE
No BK7231T build after 1.17.201 

### ISSUE THREAD

**Issue by Wolfieeewolf** [openshwprojects/OpenBK7231T_App#888]
Appears to be no BK7231T build after 1.17.201 not sure if intensional due to issues or not. Thought I'd flag it just in case it was an oversite

**Comment by openshwprojects** [comment]
Sorry for the lack of T build, it's just that we merged a LED controller code from a user and it seems he didn't include T support. I need to add a conditional for that.

**Comment by Wolfieeewolf** [comment]
All good, I'll close this off now
