### ISSUE TITLE
T34 compatibility

### ISSUE THREAD

**Issue by ec-blaster** [openshwprojects/OpenBK7231T_App#90]
Hello.

I've been reading about your effort to flash a custom firmware in these devices and I find it amazing.
I have a new Tuya wifi in-wall socket with power meter which has serious wifi stability problems, I opened it and I can see there's a "T34" chip inside. I've been reading the characteristics and it seems to be based on BK7231N (according to this [Tuya documentation](https://developer.tuya.com/en/docs/iot/t34-module-datasheet?id=Ka0l4h5zvg6j8)).

![t34 (2)](https://user-images.githubusercontent.com/8253942/171058686-1a9d5940-83af-486d-bfe1-d42a7a66dc1f.jpg)

I wonder if your project might be compatible with this chip.

Thanks.

**Comment by openshwprojects** [comment]
It is most likely already compatible and if not, then I can try adding it, if that's needed.

The only problem is I don't have any T34 chips at hand and I have never seen such a module before.

Have you tried flashing one?

**Comment by ec-blaster** [comment]
I've just flashed following your guide and the Tuya pinout documentation and it seems to work. The firmware flashes OK and I can configure the device. Now I'll try to get the GPIOS working. I'll let you know, I have some photos too.

**Comment by ec-blaster** [comment]
I'll close the issue, as T34 has proven to be compatible.
Thanks.
