### ISSUE TITLE
send MQTT request via SendGet command in autoexec.bat

### ISSUE THREAD

**Issue by Wolfieeewolf** [openshwprojects/OpenBK7231T_App#928]
Is it possible to send MQTT request via the SendGet command?

I use Zigbee2MQTT and it would be great if I could send an MQTT request to turn off a light when I press the button on my OBK switch.

something like

`addEventHandler OnClick 8 SendGet cmnd/OusideLight/PowerToggle`

**Comment by openshwprojects** [comment]
Well, aren't you looking for a Publish command?

**Comment by Wolfieeewolf** [comment]
I guess so.

I'm not really familiar with MQTT commands.

Can OBK already do something like this?

**Comment by openshwprojects** [comment]
You can do a publish in obk from script and in HA watch for it to trigger any automation you want

**Comment by Wolfieeewolf** [comment]
I tried something like this

`addEventHandler OnClick 10 publish zigbee2mqtt/lounge/set/TOGGLE`

I can see it registering in MQTT Explorer but it doesn't turn the light on or off.

I'm not very good with MQTT commands and could very well have it wrong.  I have done some searching but haven't found anything that works yet.

**Comment by openshwprojects** [comment]
What is the expected Zigbee2MQTT publish syntax? What is the topic and payload you want to send?

**Comment by Wolfieeewolf** [comment]
as per this Zigbee2MQTT site the publish syntax should be  zigbee2mqtt/FRIENDLY_NAME/set with payload {"state": "TOGGLE"}
[Zigbee2MQTT Ikea light](https://www.zigbee2mqtt.io/devices/LED1622G12.html)

Following the [MQTT topics page](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html) it should be correct but doesn't trigger the light.

Could be because it's using JSON commands. I'm not sure if OBK supports the sending of this data.

I can see that it triggers the light in MQTT Explorer but the command is not correct so doesn't turn on the light. The syntax is correct as far as I can tell.

**Comment by Wolfieeewolf** [comment]
> That is possible, but you must use a third parameter with the value of "-1" on the publish command. For example: publish zigbee2mqtt/FRIENDLY_NAME/set Toggle -1

This works perfectly :)
