### ISSUE TITLE
Timer? This isn't an issue but a function request.

### ISSUE THREAD

**Issue by hdragoon** [openshwprojects/OpenBK7231T_App#935]
Could the Timer function be implemented?

**Comment by openshwprojects** [comment]
Hello, have you looked into repeating events?

**Comment by hdragoon** [comment]
> Hello, have you looked into repeating events?

Hi, sorry for not understanding as I'm a noob, I just flashed the firmware yesterday and was trying to figure things out. Where could I look into "repeating events"?
What I mean is this 
![image](https://github.com/openshwprojects/OpenBK7231T_App/assets/62820191/b467de41-4942-4a4b-948a-143ea104879e)

**Comment by openshwprojects** [comment]
This can be done via addClockEvent command. We do not have gui for that yet

**Comment by hdragoon** [comment]
Thank you!
I'm gonna look into that.
