### ISSUE TITLE
device name on html config page <title>? 

### ISSUE THREAD

**Issue by brijins** [openshwprojects/OpenBK7231T_App#96]
Hi,

I have multiple devices running on this project firmware now.. Just a suggestion,  it would be nice to have the device name (short or full name) included in its title tag, so that it will be easy to identify them from the first glance itself. 

`<title> shortname or full name </title>`

**Comment by openshwprojects** [comment]
Huh, that's a great idea, I was silly not to think about it earlier. Wait, I'll add it today

**Comment by brijins** [comment]
sorry, I was away from home for few days. sure will do.

**Comment by openshwprojects** [comment]
Thanks, I look forward towards seeing your configuration there!

As this issue is resolved, I am closing it now
