### ISSUE TITLE
Error 404 Not found Download OpenBK7231T 1.17.334

### ISSUE THREAD

**Issue by salvomaltese** [openshwprojects/OpenBK7231T_App#992]
**Describe the bug**
Error 404 Not found Download OpenBK7231T 1.17.334 in releases

**To Reproduce**
1. Go to https://github.com/openshwprojects/OpenBK7231T_App/releases/
2. Click On any download link OpenBK7231T of 1.17.334 or 1.17.333
3. Return Error 404

**Comment by openshwprojects** [comment]
Fixed, but in general, we have already issue for that: https://github.com/openshwprojects/OpenBK7231T_App/issues/987
