### ISSUE TITLE
OpenBK7231T_1.17.335.rbl says v1.0.0

### ISSUE THREAD

**Issue by nospam2k** [openshwprojects/OpenBK7231T_App#994]
I don't think anything else is necessary. Just upgrade and look at version.

**Comment by openshwprojects** [comment]
Again, we know it:
https://github.com/openshwprojects/OpenBK7231T_App/issues/987

**Comment by sm4rk0** [comment]
First, hi there and thank you for maintaining this priceless tool!

It's not obvious that these two issues are related, lest duplicate.

Maybe pinning the original one and explaining what we could expect as a consequence of it would reduce the future duplicates?
