### ISSUE TITLE
Error 404 File not found

### ISSUE THREAD

**Issue by jonas5064** [openshwprojects/OpenBK7231T_App#997]
Error 404 File not found

[OpenBK7231T_1.17.341.rbl](https://github.com/openshwprojects/OpenBK7231T_App/releases/download/1.17.341/OpenBK7231T_1.17.341.rbl)

BTW Thanks for a fantastic jobb :-)

**Comment by openshwprojects** [comment]
We're working on it:
https://github.com/openshwprojects/OpenBK7231T_App/issues/987
